### ISSUE TITLE
exception Chinese display

### ISSUE THREAD

**Issue by AdminHcat** [RW-HPS/RW-HPS#124]
Use say command on the server

**Describe the bug**

**To Reproduce**
1. run server
2. player join server
3. use say command on the server typying some chinese
4. as u can see

**Expected behavior**
should display normally

**Screenshots**
![LY)2 _T~S5F`X$FI1HS{VYA](https://user-images.githubusercontent.com/50044729/139581390-9564ce03-9ed6-4a80-9ee5-54e05af81826.png)
![3D5 {4Z160`0RYWV%`Z2~RF](https://user-images.githubusercontent.com/50044729/139581394-6f07c20d-b272-4cb5-9521-480acac8b0b3.png)

*Pplease complete the following information:**
 - Device: PC
 - OS: Windows 10  Pro for Workstations
 - Game Version 1.14
 - Server Version 1.5.0-M2-DEV1

**Additional context**
nothing

**Comment by deng-rui** [comment]
Try using the manual start (bat) in the game directory instead of the exe

Because as far as I know, the exe starts using the system encoding, and the bat starts using UTF-8

**Comment by AdminHcat** [comment]
> Try using the manual start (bat) in the game directory instead of the exe
> 
> Because as far as I know, the exe starts using the system encoding, and the bat starts using UTF-8

tried or that

**Comment by deng-rui** [comment]
Try using UTF-8 on the server side to start, and UTF-8 on the client side
