### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by AdminHcat** [RW-HPS/RW-HPS#125]
**Describe the bug**

**To Reproduce**
1. run server
2. player join server
3. wait 1 min
4. as u can see

**Expected behavior**

**Screenshots**
client crash
![Q9E4~LMB$03`24)HRA}OLN9](https://user-images.githubusercontent.com/50044729/139581688-c03c97f2-e3c9-4692-bc43-434f46bdc7e5.png)
Server Log
![image](https://user-images.githubusercontent.com/50044729/139581826-03fc5359-fb7f-4361-a85c-1f62be3bcbe1.png)

This is client run log
![image](https://user-images.githubusercontent.com/50044729/139581720-459ca10d-3a05-4131-9359-121462759044.png)

*Pplease complete the following information:**
 - Device: PC
 - OS: Windows 10 Pro for Workstations
 - Game Version 1.14
 - Server Version 1.5.0-M2-DEV1

**Additional context**
nothing

**Comment by deng-rui** [comment]
Can you provide a more detailed Game error report?

**Comment by deng-rui** [comment]
Associated with #124
