### ISSUE TITLE
How to install mods?

### ISSUE THREAD

**Issue by PythonShadow** [RW-HPS/RW-HPS#126]
Please, explain me.

**Comment by deng-rui** [comment]
![Screenshot_2021_1004_124423](https://user-images.githubusercontent.com/39623218/140626909-26b28a0a-fb17-4e7f-be5e-162bf4bfb723.jpg)


It might help.

**Comment by PythonShadow** [comment]
Okay but I'm not so familiar in Chinese.
Also I got an error in v1.15p4 - Found unit experimentalGunship but it does not match the servers copy from internal units.

**Comment by deng-rui** [comment]
Sorry for the late reply

Currently readUnitData only supports 1.14,1.15 is not yet supported

Missing units may be using the wrong server version (use 1.5.0-M2-DEV2) ?

**Comment by PythonShadow** [comment]
Thx i will try using it

**Comment by PythonShadow** [comment]
Try to add mods support in 1.15

**Comment by deng-rui** [comment]
> Try to add mods support in 1.15

Will soon support

**Comment by PythonShadow** [comment]
Same problem in latest


> 
> 
> Okay but I'm not so familiar in Chinese. Also I got an error in v1.15p4 - Found unit experimentalGunship but it does not match the servers copy from internal units.

**Comment by PythonShadow** [comment]
> 
> 
> > Same problem in latest
> > > Okay but I'm not so familiar in Chinese. Also I got an error in v1.15p4 - Found unit experimentalGunship but it does not match the servers copy from internal units.
> 
> Not very clear, I am using the 1.15.P4 client data, I do not know if the client data is not correct, I will try to read it again
> 
> The current readmods only support 1.14
> 
> 1.15.P* support is testing

Error happened without mods

**Comment by deng-rui** [comment]
-> #70
Sup Mods (Not Read UnitData)

**Comment by deng-rui** [comment]
#130
