### ISSUE TITLE
Can I add AI to this game server?

### ISSUE THREAD

**Issue by xuange-like-python** [RW-HPS/RW-HPS#130]
I successfully ran rw-hps on my server the day before yesterday

我前天成功的在我的服务器运行了RW-HPS

But I found I couldn't add AI？！！

但是我发现我无法添加ai？！！

Is this a setup problem?

这是设置的问题吗？

If not, you can use mod to solve？？

如果不是可以用mod来解决吗

Please tell me the solution, because I need AI

请告诉我解决方法，因为我需要ai

**Comment by deng-rui** [comment]
Not supported, but you can use the REKAY protocol to get ai support

**Comment by xuange-like-python** [comment]
How to add AI using relay?

如何用relay添加ai

I need methods because I need AI

我需要方法，因为我需要ai

please

**Comment by deng-rui** [comment]
你可以在Config的DefStart(应该是）把start改为startrelayopen(好像是startopenrelay)？不是很清楚

暂时没时间去写文档

**Comment by deng-rui** [comment]
好的,非常抱歉这么晚回复
Okay, sorry for the late reply

你需要将Config.json的DefStartCommand的值start改为startrelayopen,然后运行服务端,即可体验RELAY多房间模式
You need to change the value start of DefStartCommand in Config.json to startrelayopen, then run the server, you can experience RELAY multi-room mode

如果不希望是多房间,那么你需要把SingleUserRelay改为true,如果需要启用Mod,那么还需要将SingleUserRelayMod改为true
If you do not want to be multi-room, then you need to change SingleUserRelay to true, if you need to enable Mod, then you also need to change SingleUserRelayMod to true

**Comment by xuange-like-python** [comment]
你太客气了

我才应该感谢你

我还有一个问题

如何将自己服务器添加到官方的服务器列表里

我想让更多人一起玩

**Comment by deng-rui** [comment]
您可以在控制台使用help来查看命令

上列表的命令为
upserverlist

**Comment by xuange-like-python** [comment]
那有没有一种mod可以自动帮忙上列表吗？？

**Comment by deng-rui** [comment]
> 那有没有一种mod可以自动帮忙上列表吗？？

Mod上自动列表？我觉得这不可能
以及 我可能不太清楚您表达的意思

是Mod的服务器上列表？
   按照上文启用配置 用命令即可
还是Mod来让服务器上列表
   不清楚 理论不行

**Comment by xuange-like-python** [comment]
对了

我·发现在relay模式下在游戏内好像无法使用命令

**Comment by deng-rui** [comment]
> 对了
> 
> 我·发现在relay模式下在游戏内好像无法使用命令

是的 ，在RRLAY下的控制台也只能使用基础命令，kick ban kill等无法使用

**Comment by xuange-like-python** [comment]
对了上面说的意思是
开启服务器时自动执行 upserverlist 这个指令
或者在结束一场游戏时自动执行upserverlist指令

**Comment by deng-rui** [comment]
> 对了上面说的意思是 开启服务器时自动执行 upserverlist 这个指令 或者在结束一场游戏时自动执行upserverlist指令

执行一次upserverlist可以一直到服务器exit或者你执行removeserverlist

**Comment by deng-rui** [comment]
即 只要网络没问题 那你就能一直在列表显示

**Comment by deng-rui** [comment]
如果要上列表
我建议修改Config的服务器名字(⊂((・▽・))⊃

**Comment by xuange-like-python** [comment]
好的谢谢

**Comment by xuange-like-python** [comment]
对了

这个服务器可以监听ipv6地址吗

**Comment by deng-rui** [comment]
> 对了
> 
> 这个服务器可以监听ipv6地址吗

或许吧？但是list似乎不支持ipv6？

**Comment by deng-rui** [comment]
你可以尝试一下，我的开发环境不存在ipv6┐( ∵ )┌

**Comment by xuange-like-python** [comment]
好
