### ISSUE TITLE
上传服务器列表后显示端口未开放

### ISSUE THREAD

**Issue by CLAY-2333666** [RW-HPS/RW-HPS#131]
我是用樱花穿透开的服因为没有公网ip，不上传服务器列表可以正常连接，上传后不行并且显示端口未开放。 
樱花隧道是127.0.0.1:5123
在阿里云服务器试过，上传服务器列表后连接正常

**Comment by CLAY-2333666** [comment]
![3bdd0321ac0e9db45c08b8c543e5098](https://user-images.githubusercontent.com/34829033/144724666-3d60a531-67fd-4bec-84de-f15325ef7af4.png)

**Comment by deng-rui** [comment]
没有公网ip无解，使用FRP/NGROK等无法上列表

请使用IPV4
