### ISSUE TITLE
建议：标签改为英语

### ISSUE THREAD

**Issue by cloudwindy** [RW-HPS/RW-HPS#135]
我不清楚你这个项目到底是面向哪国人，但是现在既然你写了英文的README.md，那么最好整个项目都统一一下。

**Comment by deng-rui** [comment]
已注意 将在本周进行标准化统一

**Comment by deng-rui** [comment]
非常感谢您的建议

**Comment by cloudwindy** [comment]
另外请检查PR#133（README修订建议）

**Comment by deng-rui** [comment]
Modification completed
