### ISSUE TITLE
关于授权许可的问题

### ISSUE THREAD

**Issue by cloudwindy** [RW-HPS/RW-HPS#136]
你的授权许可使用的是GNU/APL，简要内容已经由Github概括：
Permissions
 Commercial use
 Modification
 Distribution
 Patent use
 Private use
也就是说，商业用途是可以的，再发布也是允许的，但是看起来你的README上标明不能用于商业用途，再发布要注明原作者，到底是以哪个为准呢？

**Comment by 1dNDN** [comment]
The AGPL does not prohibit commercial use, but requires publishing or transmitting the source code upon request.

**Comment by 1dNDN** [comment]
"transmitting the source code upon request" means that anyone using the program can request the source code. The one who doesn't use it can't.

**Comment by cloudwindy** [comment]
感谢两位清晰的说明！
Thank you for the explanation!
