### ISSUE TITLE
服务器长期运行出现bug

### ISSUE THREAD

**Issue by xuange-like-python** [RW-HPS/RW-HPS#139]
我发现大概服务器持续运行一上午左右时间的时候

再次开始游戏客户端会发生一个致命的错误

![avatar](https://www.xgboke.top/img/img/1639300237897.jpg)

这是游戏报错截图

![avatar](https://www.xgboke.top/img/img/1639300237891.jpg)

这是系统报错提示

求解决

**Comment by deng-rui** [comment]
#123

**Comment by xuange-like-python** [comment]
_那么该怎么解决？？_

**Comment by xuange-like-python** [comment]
***我不会java***

**Comment by deng-rui** [comment]
目前暂时无方法，初步看起来是定时线程出现问题

另一个解决方案：
使用RELAY协议？（可能也有bug？）

具体修复需要等待2.x版本

**Comment by xuange-like-python** [comment]
好吧，如果可以的话，希望2.x版本支持ipv6

**Comment by deng-rui** [comment]
> 好吧，如果可以的话，希望2.x版本支持ipv6

我记得可以IV6,但是luke的列表好像不是完全支持（残废）
得等luke了

**Comment by xuange-like-python** [comment]
好的，加油，虽然我也想加人但可惜还不会java，而且时间也不够（高中生）
现在自会python，和一点点js
wwwwww

**Comment by xuange-like-python** [comment]
我今天想打开服务器然后上传list，然后报错了，error
而且服务器没有上传到列表，是不支持了吗
服务器是最新版的

**Comment by deng-rui** [comment]
> 我今天想打开服务器然后上传list，然后报错了，error 而且服务器没有上传到列表，是不支持了吗 服务器是最新版的

目前计划在 2.X - RC 发布前, UpList-API暂时对外停止服务
因为在 1.x 的Server/Relay协议均存在Bug , 不适合对外提供服务

**Comment by xuange-like-python** [comment]
好吧，我认为这是明智的选择。
