### ISSUE TITLE
upserverlist命令返回Error以及关闭服务器时出现的问题

### ISSUE THREAD

**Issue by 493505110** [RW-HPS/RW-HPS#140]
![image](https://user-images.githubusercontent.com/29498336/147376956-87454f90-2db1-43b7-b5cc-d0b20163af27.png)
并且stop时出现以下错误
![image](https://user-images.githubusercontent.com/29498336/147376972-4fac3d3f-cdb7-49b1-a923-1fec1df7495b.png)
如果直接exit则这样
![image](https://user-images.githubusercontent.com/29498336/147376983-b6c92d46-1394-4c43-885b-95afeb59bc06.png)

**Comment by deng-rui** [comment]
UpList接口目前暂时对外服务
更多信息请查看 #139

**Comment by deng-rui** [comment]
对于Exit导致的报错,应该是正常的 但是这个错误不应该在用户层出现 ( 我会尝试解决
