### ISSUE TITLE
自定义上列表后玩家点击列表进入的服务器ip

### ISSUE THREAD

**Issue by DaiyunYang** [RW-HPS/RW-HPS#142]
个人电脑开服用frp内网穿透之后用内网穿透服务器的ip和端口可以进入服务器但是在列表显示的房间仍然显示为不开放也无法点击进入，有办法自定义在list点击之后进入的ip和port吗？

**Comment by deng-rui** [comment]
很抱歉，无法自定义IP
官方的列表服务是直接读取请求IP 没什么办法伪造

你可以尝试在frp Server转发HTTP请求
