### ISSUE TITLE
可以调用玩家地图

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#163]
希望可以做到服务器调用玩家设备的自定义地图，而不仅仅仅限于服务器已放的地图，具体和CN服务器差不多那个样

**Comment by deng-rui** [comment]
那可能需要使用RELAY协议运行服务器
（参见文档）
就目前而言，Server协议无法读取到客户端的地图数据，同时，也没有相关网络接口，需要游戏作者进行兼容或者对游戏作出适应性修改
