### ISSUE TITLE
地图/afk锁定不应因为重启服务器而重置

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#166]
afk和地图锁定在重启服务器后需要重新设置，个人感觉应该在- [ ] 重启服务器后依然保持重启前的选择
```
isafk <off/on> - 是否禁止AFK
maplock <off/on> - 锁定游戏地图
```
其中的`maplock <off/on> - 锁定游戏地图`
感觉应该改成`maplock <地图名> [off/on] - 锁定游戏地图`顾名思义**maplock后加地图名则锁定某个地图，而不是进入服务器选择好地图后再后台输入指令锁定**
而如果地图名为空白则取消锁定，后面的`[off/on]`则为可选选择也就是可以填也可以不填

**Comment by deng-rui** [comment]
我认为也应该是这样
所以maplock将会修改为maplock <地图名> 地图名为空白则取消锁定
isafk将会更改为afklock on/off

这两个的数据将会进行持久化(即存储到Setting内)
