### ISSUE TITLE
后台输入say 文字时游戏内出现乱码

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#167]
在后台输入列如`say 你好`在后台显示正常，但是在游戏内却显示`server：乱码**具体乱码的字符我这里打不出来。。。`**，估计是编码问题，但我具体怎么修复我不清楚望解决（换服务器也是一样的问题）

**Comment by deng-rui** [comment]
你可以使用项目下的start.bat/sh来尝试运行服务器

我建议手动指定UTF-8，因为JVM默认使用系统编码， 部分系统为GBK 导致乱码

**Comment by Mitpoppy** [comment]
> 你可以使用项目下的start.bat/sh来尝试运行服务器
> 
> 我建议手动指定UTF-8，因为JVM默认使用系统编码， 部分系统为GBK 导致乱码

好的，我试了一下项目那里的bat文件解决了，我之前是自己纯写的`java -jar server.jar`
