### ISSUE TITLE
Packet格式中文文档

### ISSUE THREAD

**Issue by wihn2021** [RW-HPS/RW-HPS#173]
求服务器数据包格式，如startgame时发送packet的内容是什么，客户端发来的数据包格式是什么。

**Comment by deng-rui** [comment]
目前暂时无法确定文件格式

如果可以 我希望您可以提供一个文件格式

MinXyzGo :
[type:160,msg:String,xx:x]

来自我的想法 : 
Receive :
{
Type:160(ServerInfo),
Data: [
msg:String
version:Int
]
}

我无法找到比较好的格式

**Comment by wihn2021** [comment]
可否关于msg:string中的命令/参数等写一点说明？比如startgame时msg里是xxx，kick时msg里是xxx

**Comment by deng-rui** [comment]
> 可否关于msg:string中的命令/参数等写一点说明？比如startgame时msg里是xxx，kick时msg里是xxx

或许会 我会考虑参考miairi doc

**Comment by wihn2021** [comment]
。。。miairi是什么🤔
