### ISSUE TITLE
玩家游戏不同步，导致多个玩家画面不一样

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#174]
`在游戏中例如：两个玩家，有一个玩家有延迟等什么情况然后会和另一个玩家的游戏画面不同步，就比如a玩家现在飞机移动到左上角了，而b玩家（不同步）却还显示在a玩家还没有造出飞机的时候，而且服务器不会自动同步。`
**该现象在生存类地图里常发生，具体原因不清楚。**

- 个人提供可选方案：

- [ ] 1.个人认为可以尝试添加服务器过一段时间自动同步，但是经常加载可能会影响游戏体验

- [ ] 2.可以尝试添加玩家命令比如/Resynchronize（建议缩短）玩家可以在游戏内自己输入命令同步

**Comment by deng-rui** [comment]
您好 我建议您在游戏里使用 [.help] 查看一下命令

对于第二个手动同步 是有支持命令的 [.sync]

对于第一个 请参阅其他issus #158
