### ISSUE TITLE
服务器信息打印出现误导

### ISSUE THREAD

**Issue by SinoAHpx** [RW-HPS/RW-HPS#175]
+ 服务器：Windows Server 2019
+ RW-HPS版本：5.2.0
+ 铁锈战争版本：1.14

![image](https://user-images.githubusercontent.com/34391004/159126927-f3edebbe-30c4-452a-8ee2-6625e5105bfd.png)
![image](https://user-images.githubusercontent.com/34391004/159126942-721f3850-35d5-466c-b803-26358c96068f.png)
端口已放行
![image](https://user-images.githubusercontent.com/34391004/159127028-6559870b-48d0-4f93-a875-0ec356e064c6.png)
`直接加入`服务器显示如上
`直接加入`时使用的地址为`<服务器ip地址>:<端口>`

**Comment by deng-rui** [comment]
看起来 您防火墙并没有打开
因为upserverlist后的端口开放检测是失败的

**Comment by deng-rui** [comment]
哦 可能是我想错了
您的防火墙开放的是UDP而不是TCP
游戏默认使用TCP
UDP只是测试版（稳定性我认为并不好，不建议使用）

**Comment by deng-rui** [comment]
处于稳定性原因
暂时取消支持RUDP

**Comment by SinoAHpx** [comment]
问题解决了（
实际上这个问题是我的VPS提供商腾讯云的锅，因为腾讯云的机器默认关闭windows系统自带的防火墙，所以需要在[腾讯云控制台](https://console.cloud.tencent.com/)放行端口

**Comment by SinoAHpx** [comment]
~~我觉得这应该被写进FAQ~~

**Comment by deng-rui** [comment]
> ~~我觉得这应该被写进FAQ~~

~~我看行~~
