### ISSUE TITLE
开启服务器后在控制台可直接重载配置文件

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#177]
在控制台内可直接重载已改过的配置文件

- [x] #178

输入命令重载就不用每次更新还要重启服务器更新了
`（如果可以的话建议热加载）`

**Comment by deng-rui** [comment]
需要完成 #84 

就目前的垃圾代码而言 可能需要一个大改动来使其支持热停止 (即stop)

**Comment by Mitpoppy** [comment]
> 需要完成 #84 
> 
> 就目前的垃圾代码而言 可能需要一个大改动来使其支持热停止 (即stop)
> 

咕到明年嘛| ू•ૅω•́)ᵎᵎᵎ

**Comment by deng-rui** [comment]
> > 需要完成 #84 
> > 
> > 就目前的垃圾代码而言 可能需要一个大改动来使其支持热停止 (即stop)
> > 
> 
> 咕到明年嘛| ू•ૅω•́)ᵎᵎᵎ

咕~
