### ISSUE TITLE
对于nat服务器的进一步建议

### ISSUE THREAD

**Issue by xuange-like-python** [RW-HPS/RW-HPS#180]
我用frp这个内网穿透工具在我服务器搭建了服务端

然后在家的树莓派使用frp客户端连接
并且打开本地5123端口映射到服务器的5123端口

用树莓派打开rw-hps服务端
使用uplist add 命令

在官网列表增加了有服务器
但是ip地址不一样
所以无法连接

我建议uplist加一个自定义ip的功能

**Comment by deng-rui** [comment]
无法解决
这个问题是由于 列表服务器直接获取http请求的ip 无法进行伪造 （CF CDN标识头）~~可能是我技术力不够 我会抽时间看看~~

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/186302658-0bb32db9-b365-4efb-9924-ae8760c3972e.png)
能否覆盖此请求头来解决?

**Comment by deng-rui** [comment]
> ![image](https://user-images.githubusercontent.com/29498336/186302658-0bb32db9-b365-4efb-9924-ae8760c3972e.png) 能否覆盖此请求头来解决?

无效

目可能是根据 Connect 的 IP判断 而不是 头
