### ISSUE TITLE
重连后其他玩家无法控制单位并且卡顿

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#181]
开始游戏后莫名原因断开，然后重连会导致没有退出的玩家卡住无法正常游戏，**左上角聊天栏一直显示同步中**。问题很大，望解决（在开了模组的服里出现明显）
`并且会一直卡住，等了半个小时，还是一样，有时候时好时坏，比如刚显示同步一下就好了，然后又断了一直重复。`
![Screenshot_2022-03-30-15-25-14-79_6483dd1576f1330fe7c408604fe48ee1.jpg](https://user-images.githubusercontent.com/89001400/160785987-f5b55a39-6d8e-40b7-84c2-536c9c83c0dc.jpg)

**Comment by deng-rui** [comment]
#158 
我到时候尝试看看1.14的快速同步

可能需要模拟层

**Comment by deng-rui** [comment]
去掉了 Object.wait 尝试使用回调
