### ISSUE TITLE
添加人机

### ISSUE THREAD

**Issue by XIAOYUANXIONG** [RW-HPS/RW-HPS#183]
为什么RW-HPS主页面可以加人机，这个不行

**Comment by 493505110** [comment]
RELAY协议可以




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "RW-HPS/RW-HPS"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Apr 5, 2022 09:43 AM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[RW-HPS/RW-HPS] 添加人机 (Issue #183)





 
为什么RW-HPS主页面可以加人机，这个不行

**Comment by deng-rui** [comment]
问题已存在
#35 

AI你可以使用RELAY协议 目前无模拟层
无法实现AI
