### ISSUE TITLE
建议添加mod选择性加载功能

### ISSUE THREAD

**Issue by MZZZ-T** [RW-HPS/RW-HPS#184]
- [ ] > 添加一个在游戏房间内，游戏开始前选择性加载和开关MOD的命令
——————————————就像换地图一样换MOD！

**Comment by deng-rui** [comment]
下次也不一定

**Comment by deng-rui** [comment]
服主自己调整 data/mods 罢
文件后缀改一下就可以不加载了

只会读取 `rwmod` `zip`
