### ISSUE TITLE
MOD房在列表的地图名显示为动态

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#185]
开启MOD的房间在外面列表地图名显示为动态的mod名（在 #184 mod开关的基础上），就比如开启MOD后地图名前面（或者自定义名字前面）显示[xxxmod]+地图名（或自定义名字）这样的话方便玩家切换mod进服
`**（估计又要咕咕咕一段时间）**`

**Comment by deng-rui** [comment]
那么这样的话 如果有多个Mod呢

**Comment by deng-rui** [comment]
多个mod难道取第一个吗 (
我也想过这个问题 我觉得可以抄袭RCN
版本号改为
1.14-MOD

**Comment by 493505110** [comment]
循环显示或者只显示mod数量应该就行了吧


------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "RW-HPS/RW-HPS"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Apr 5, 2022 01:48 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;Re: [RW-HPS/RW-HPS] MOD房在列表的地图名显示为动态 (Issue #185)





 
那么这样的话 如果有多个Mod呢

**Comment by deng-rui** [comment]
> 循环显示或者只显示mod数量应该就行了吧
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: "RW-HPS/RW-HPS" ***@***.***&gt;; Date:&nbsp;Tue, Apr 5, 2022 01:48 PM ***@***.***&gt;; ***@***.***&gt;; Subject:&nbsp;Re: [RW-HPS/RW-HPS] MOD房在列表的地图名显示为动态 (Issue #185) 那么这样的话 如果有多个Mod呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

循环岂不是更离谱 ( , 玩家一看 咦 我的Mod呢 (不

**Comment by 493505110** [comment]
进入服务器前会有个窗口询问是否加入和一些服务器的信息，能不能更改那个窗口里的内容？

**Comment by deng-rui** [comment]
> 进入服务器前会有个窗口询问是否加入和一些服务器的信息，能不能更改那个窗口里的内容？

那是RELAY协议 ( 对于Server协议用这个窗口真的好吗 (

**Comment by 493505110** [comment]
![Screenshot_2022-04-05-13-58-23-878_com corrodingg](https://user-images.githubusercontent.com/29498336/161688352-2f9adb9a-6355-4068-98b4-6e20e212b303.jpg)
(指这个窗口)

**Comment by deng-rui** [comment]
> ![Screenshot_2022-04-05-13-58-23-878_com corrodingg](https://user-images.githubusercontent.com/29498336/161688352-2f9adb9a-6355-4068-98b4-6e20e212b303.jpg) (指这个窗口)

没有办法 (

User Map Version这三个没一个能给Mod显示用的 (

**Comment by Mitpoppy** [comment]
> > ![Screenshot_2022-04-05-13-58-23-878_com corrodingg](https://user-images.githubusercontent.com/29498336/161688352-2f9adb9a-6355-4068-98b4-6e20e212b303.jpg) (指这个窗口)
> 
> 没有办法 (
> 
> User Map Version这三个没一个能给Mod显示用的 (

不能试试在那个窗口上再加一行MODS嘛

**Comment by 493505110** [comment]
在版本最后加个\n应该能...吧

**Comment by deng-rui** [comment]
> 在版本最后加个\n应该能...吧

你,,, 试试?

**Comment by deng-rui** [comment]
![Screenshot_20220416_151904_8631dd15e8465f7b557741726434b4fd.jpg](https://user-images.githubusercontent.com/39623218/163666148-efca5b30-fdb7-44df-80da-6d656d778e39.jpg)

使用/n \n 各种奇奇怪怪的方法 均无效

看起来是List过滤了这些参数
