### ISSUE TITLE
游戏结束后可选择是否继续留在服务器并准备进行下一局游戏

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#191]
在一局游戏结束之后出来的那个结束界面可以添加**返回服务器/或者下一局游戏**而不是单纯的继续游戏和完成游戏。返回服务器主要作用是返回游玩的这个服务器，可以不用在列表重新找到，直接返回到服务器
`优点：节约时间`
~~（不过我相信鸽子dr肯定不会做的）~~

**Comment by deng-rui** [comment]
但是没有办法判定胜利
可能会被搁置 需要模拟层

但可以实现一个 vote nextGame
或者一个超时机制 像Auto Server一样
服务器玩多长时间后强制Gameover 避免一直占用

**Comment by deng-rui** [comment]
需要 # 195 同步进行

**Comment by deng-rui** [comment]
1.15 有了回到战役室, 故本问题无意义
