### ISSUE TITLE
添加全局管理员（adnin）

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#192]
添加全局管理员后，那个玩家在任何时候进入服务器都将会是管理员，并且拥有房主的一切权限（主要是防止有的玩家在服务器挂机一直不开，但是也不让别的玩家afk，搞事情的那种，经常见）
~~（也可以服主装X）~~
~~（不过我相信鸽子dr肯定不会做的）~~

**Comment by deng-rui** [comment]
目前的admin命令就是全局管理员

如果你指的是 RW-HPS全部服务器的管理员 那我认为没有必要

这种的admin需要一个中心平台管理 但是并没有什么用
