### ISSUE TITLE
添加配置文件中进入房间后聊天栏显示的超链接变量

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#194]
在配置文件中可以输入比如：
`欢迎来到本服务器\n本服务器官网：address@点我查看官网#blog.114524.xyz`
在游戏内显示就是：（可点击跳转浏览器或者内置浏览器的网页）
**欢迎来到本服务器
本服务器官网：[点我查看官网](https://blog.someo.top/)**

**Comment by deng-rui** [comment]
游戏本体不支持
