### ISSUE TITLE
使用docker方式运行的怎么使用指令？

### ISSUE THREAD

**Issue by fncheng** [RW-HPS/RW-HPS#203]
help start这类指令

`docker exec -it rw-hps-container bash` 后没法进入java进程 的交互

有大佬知道吗

**Comment by deng-rui** [comment]
你可以试试在docker开一个bash出来 在bash里运行jar?

**Comment by fncheng** [comment]
> 你可以试试在docker开一个bash出来 在bash里运行jar?

但是docker 容器启动的时候会自动执行java -jar Server.jar , 并且进程pid 为1，再启一个后 top查看会有两个进程
kill 1 容器就关闭了

**Comment by deng-rui** [comment]
> > 你可以试试在docker开一个bash出来 在bash里运行jar?
> 
> 但是docker 容器启动的时候会自动执行java -jar Server.jar , 并且进程pid 为1，再启一个后 top查看会有两个进程 kill 1 容器就关闭了

快来问一问这个 @yiyungent  docker的sh他写的 (逃

**Comment by yiyungent** [comment]
> help start这类指令
> 
> `docker exec -it rw-hps-container bash` 后没法进入java进程 的交互
> 
> 有大佬知道吗

用 docker attach 进入这个进程1
