### ISSUE TITLE
新的GUI控制面板

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#213]
直接打开一个gui控制面板启动服务器，而不是用bat启动jar

> 优点：方便快捷
> 缺点：咕咕咕

**Comment by deng-rui** [comment]
你来

**Comment by Mitpoppy** [comment]
> 你来

阿这

**Comment by wihn2021** [comment]
直接接入某些面板不就行了？[比如这种](https://github.com/MCSManager/MCSManager)

**Comment by wihn2021** [comment]
> 直接接入某些面板不就行了？[比如这种](https://github.com/MCSManager/MCSManager)

然而本质上还是命令行

**Comment by deng-rui** [comment]
[ MCSM / 翼龙 ] 面板解决问题
