### ISSUE TITLE
6.0.0版本的不同步报错

### ISSUE THREAD

**Issue by Qiuye023** [RW-HPS/RW-HPS#221]
似乎是只出现在开局的同步信息
![image](https://user-images.githubusercontent.com/101028621/172037907-7aa52ff3-8bf5-44ee-b828-cdf5c2caa8ac.png)

![@SW4HXI)$6SO%UJZ4}39PJI](https://user-images.githubusercontent.com/101028621/172037915-117f62c3-36ad-4e78-a3cf-5ba637b883c2.png)

**Comment by deng-rui** [comment]
![image](https://user-images.githubusercontent.com/39623218/172618019-e31bbc85-327b-4ad5-9394-3a90723bb13b.png)

在 3P内尝试进行游戏 短线重连也并没有出现

可能是 Tick Thread 过早开始
