### ISSUE TITLE
天选模式

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#223]
天选模式玩法顾名思义，可以通过模式选择来选择天选模式
### **天选模式**：

> 房主可以自由的选择指定一名玩家成为天选者，或者选择由系统随机抽取一名玩家为天选者。

### **具体玩法：**

>  被指定/随机选到的那名玩家为天选者，可以拥有和单人沙盒模式一样的权限，无视建筑速度，无视生成兵的速度（引用 #199 ），并且可以在沙盒模式的基础上让那名玩家可以填海造地（就是可以使用地图编辑器中的那种方块来铺设地面/海洋）还可以直接控制其他玩家的单位/建筑，还有单人沙盒模式中的命令全部能用
### **服务器：**
> 在后台命令或配置文件可以选择固定模式（即进入服务器就是某种模式不可以改变）
> 在后台命令或配置文件可以选择ban某种模式（即该模式不可选择）

**Comment by deng-rui** [comment]
类似#199

**Comment by deng-rui** [comment]
填海造地我觉得不可能

**Comment by Mitpoppy** [comment]
> 填海造地我觉得不可能

技术层面实现不了嘛（本质上感觉应该就和我的世界修改地图一样吧）

**Comment by wihn2021** [comment]
铁锈本身就没有动态改地图的机制吧

**Comment by MZZZ-T** [comment]
动态生成单位还有可能，动态改地图估计得让luke搞

**Comment by Mitpoppy** [comment]
> 动态生成单位还有可能，动态改地图估计得让luke搞

服务器能做到和mod一样嘛，我看mod好像有个可以直接生成草地什么的，不清楚是不是单位

**Comment by MZZZ-T** [comment]
> 

那不就是做了个mod

**Comment by MZZZ-T** [comment]
> > 动态生成单位还有可能，动态改地图估计得让luke搞
> 
> 服务器能做到和mod一样嘛，我看mod好像有个可以直接生成草地什么的，不清楚是不是单位

注意像石笋/墙这类是属于单位的，不是像水/陆地/岩浆一样的地图图层

**Comment by Mitpoppy** [comment]
> > > 动态生成单位还有可能，动态改地图估计得让luke搞
> > 
> > 服务器能做到和mod一样嘛，我看mod好像有个可以直接生成草地什么的，不清楚是不是单位
> 
> 注意像石笋/墙这类是属于单位的，不是像水/陆地/岩浆一样的地图图层

阿这，不好意思我没做过地图不清楚建筑和单位区别233（长知识了）
