### ISSUE TITLE
多模式选择

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#224]
在房主创建房间后可以在gui面板（或是聊天栏输入命令）来切换游戏的玩法/模式
比如：

> 经典模式
>> 就是最普通的原版游戏模式

> MOD模式
>> 房主可以自由选择MOD进行游戏（建议联网弄一个MOD表并在线下载更新，由社区维护（~~或者是用现成的Github弄一个md表然后游戏内通过cdn加速后读取MOD信息并返回游戏中，然后玩家选择是否下载，点击下载后通过md中的某个mod信息中的直链直接下载到玩家本地（我感觉Dr不会听我的）~~））

> 娱乐模式
>> 娱乐模式引用dr的 #199 

>天选模式
>> 天选模式引用Mitpoppy的 #223

**Comment by deng-rui** [comment]
mod暂时不考虑任何在线平台

因为你圈版权问题麻烦
