### ISSUE TITLE
添加最长开局时间限制

### ISSUE THREAD

**Issue by MZZZ-T** [RW-HPS/RW-HPS#226]
在Config.json文件内设置单局游戏最长开局时间，超过时间延时1min强行结束本轮游戏

**Comment by MZZZ-T** [comment]
最好在到时间延时前提前发消息说明一下，或者在游戏开始时说明最长开局时间

**Comment by MZZZ-T** [comment]
这个建议似乎在#191 中有所提及

**Comment by deng-rui** [comment]
Def : 300 Min

Config Key : 
`MaxGameTime` : `18000` (300*60s)

**Comment by MZZZ-T** [comment]
nice
