### ISSUE TITLE
服务器版本向下兼容（游戏多版本共存）

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#227]
比如适配1.15的客户端游戏的服务器
（~~虽然没出不过我感觉还是可以想想的~~）
让他可以开启或关闭兼容1.14甚至1.13，1.12等
（好像没有联机模式233）
然后1.14等...的游戏客户端就能进入1.15的服务器，不过bug应该是会有的
~~（向上兼容我感觉做不到）~~

**Comment by MZZZ-T** [comment]
6.0.0貌似可以开启兼容1.14的模式，在6.0.0-DEV3版本的 注 中有所提及

//注
//您可以使用 [plugin help] 来查看和安装 1.14 的协议 来让服务器支持 1.14 GameServer

**Comment by MZZZ-T** [comment]
在最新版本也有所提及，至于更老的版本就不清楚了（去问dr

//WARN
//This server is 1.15.P8, you can use the plug-in to support 1.14
//RELAY is common for 1.14/1.15

**Comment by Mitpoppy** [comment]
> 在最新版本也有所提及，至于更老的版本就不清楚了（去问dr
> 
> //WARN
> //This server is 1.15.P8, you can use the plug-in to support 1.14
> //RELAY is common for 1.14/1.15

dr。。。（狗都不问@deng-rui | ू•ૅω•́)ᵎᵎᵎ

**Comment by deng-rui** [comment]
> > 在最新版本也有所提及，至于更老的版本就不清楚了（去问dr
> > 
> > //WARN
> > //This server is 1.15.P8, you can use the plug-in to support 1.14
> > //RELAY is common for 1.14/1.15
> 
> dr。。。（狗都不问@deng-rui | ू•ૅω•́)ᵎᵎᵎ

爬

**Comment by deng-rui** [comment]
看起来是可以的 类mc喷泉

**Comment by deng-rui** [comment]
但是单位没办法一样（

我dev3说的是核心协议

并不算版本共存

**Comment by deng-rui** [comment]
测试失败 单位数据不同步

**Comment by Mitpoppy** [comment]
> 测试失败 单位数据不同步
> 

不能多版本共存但单位数据按某个版本的数据统一嘛
