### ISSUE TITLE
服务器支持开局后新进入玩家（观战）

### ISSUE THREAD

**Issue by deng-rui** [RW-HPS/RW-HPS#229]

**Comment by MZZZ-T** [comment]
好想法

**Comment by MZZZ-T** [comment]
那么是在玩家进房间的时候选，比如//这个房间已经满人啦，但您可以连接xx.xxx.xxx.xx（ip地址）进行观战//
还是直接让玩家进房，只在json文件里面让服主选是否启用观战模式？

**Comment by deng-rui** [comment]
后者

**Comment by deng-rui** [comment]
> 那么是在玩家进房间的时候选，比如//这个房间已经满人啦，但您可以连接xx.xxx.xxx.xx（ip地址）进行观战//
> 还是直接让玩家进房，只在json文件里面让服主选是否启用观战模式？

后者

**Comment by x-xiao98** [comment]
Dr什么时候研究一下这个呢

**Comment by deng-rui** [comment]
阳了肺炎没时间

**Comment by deng-rui** [comment]
通过占用一个玩家位, 实习此功能
