### ISSUE TITLE
新的RW多服务器启动器

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#236]
### RW服务器启动器
链接：[https://github.com/wanan12138/RW-Launcher](https://github.com/wanan12138/RW-Launcher)
尚末完成，正在开发
### 介绍
RW-HPS服务端多服启动器，是RW-HPS第一个服务器启动器，启动器运行于Windows操作系统上，其他系统未适配，启动器正在高频率持续迭代中，可能会有一些小bug，可以提交iss以告诉我们，让我们更精确的定位bug。
RH-HPS启动器为图形化启动器，简去了之前需要打开命令提示符（cmd）用命令运行的操作，现在，你只需要打开一个启动器面板就能轻松的开启多个服务器，并且是可视化图形操作，让您用的安心，用的放心。

**Comment by deng-rui** [comment]
你自己动手

**Comment by Mitpoppy** [comment]
> 你自己动手

自己动手丰衣十足 ~~（果断拉上晚安）~~

**Comment by deng-rui** [comment]
https://github.com/wanan12138/RW-Launcher
