### ISSUE TITLE
可自定义向服务器内添加背景音乐

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#239]
**功能介绍：**
如标题所示服主可以自定义向服务器内添加音乐 ~~（bgm）~~ 并且玩家加入游戏后循环播放音乐
**拓展玩法：**
`前提是服主可在服务器配置文件添加多个音乐`
1. 自选功能

> 玩家可以通过gui/指令自己选择要循环播放的音乐

2. 多种播放方式

> 玩家可以使用gui/指令（或者后台默认）等方式选择游戏内 **循环** /  **顺序** / **随机** 的播放方式

 **tips：** tm游戏时间这么长我想听个音乐怎么了， ~~小拳拳打Dr~~

**Comment by deng-rui** [comment]
服务器并无此协议
