### ISSUE TITLE
显示正在使用的mod

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#240]
在游戏内未开始游戏可使用命令显示正在使用的mod
在游戏开始后面用命令显示正在使用的mod
类似 #225

**Comment by deng-rui** [comment]
mods显示的均为使用中的

你可以改文件后缀来让服务器不加载它

**Comment by Mitpoppy** [comment]
> mods显示的均为使用中的
> 
> 你可以改文件后缀来让服务器不加载它
> 
> 使用 reloadmods 来重新加载

我是指在游戏里面而不是后台

**Comment by deng-rui** [comment]
> > mods显示的均为使用中的
> > 你可以改文件后缀来让服务器不加载它
> > 使用 reloadmods 来重新加载
> 
> 我是指在游戏里面而不是后台

并没有适用范围
客户端似乎没有重加载机制
