### ISSUE TITLE
时间记录统计

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#243]
**功能介绍：**
在游戏中可以用 `命令/GUI（最好）/显示在屏幕上的时间悬浮文字` 来显示本局游戏时间，动态统计，不过我感觉如果实现不容易的话，可以试试某些地图中使用的在消息那里，过一段时间发一次消息 **（内容是显示本局游戏时长：xxx或者是已经经过了多长时间）**

**Comment by deng-rui** [comment]
悬浮窗?
你在想桃子吃 , 等哪年luke支持了再说

目前只能在左上角直接发消息

**Comment by Mitpoppy** [comment]
> 悬浮窗?
> 你在想桃子吃 , 等哪年luke支持了再说
> 
> 目前只能在左上角直接发消息

桃子？赶快给我吃🌚

我想法独特，建议让我当策划🤣
