### ISSUE TITLE
游戏中定时公告

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#244]
**功能介绍：**
在游戏中定时发送公告消息
**功能配置：**
在后台 `命令/配置文件` 中可以设置公告内容以及公告定时发送的时间

**Comment by deng-rui** [comment]
适用范围是什么 ? (
这样做有什么意义

**Comment by Mitpoppy** [comment]
> 适用范围是什么 ? (
> 这样做有什么意义

比如。。。更新维护什么的？
或者。。。宣传广告？！我也不怎么清楚有啥用，单纯想到之前做我的世界有个公告系统，感觉应该有点用吧。。。| ू•ૅω•́)ᵎᵎᵎ

**Comment by MZZZ-T** [comment]
> 

不建议在服务器中加入任何形式的广告支持，这玩意和商业行为差不多。。。自己用就行了吧，公房开太多广告玩家反而容易产生对服务器或者战队的负面印象

**Comment by deng-rui** [comment]
> > 
> 
> 不建议在服务器中加入任何形式的广告支持，这玩意和商业行为差不多。。。自己用就行了吧，公房开太多广告玩家反而容易产生对服务器或者战队的负面印象

很奇怪 mail回的消息这里不显示

那么我就再写一遍罢 :
加了 它会不会用还是个问题
