### ISSUE TITLE
限制单一IP进入列表的数量

### ISSUE THREAD

**Issue by MZZZ-T** [RW-HPS/RW-HPS#245]
限制一个公网IP只能开1~2个服进入公共列表
现在公房某些服主开太多相似的房，一个是供给大于需求，另一个玩家很容易对服务器产生负面看法
同时建议对以前的版本也添加限制（如果可能的话）

**Comment by deng-rui** [comment]
# WARN
## 弃用版本
API-V2 API-V3 API-V4
## 原因
如上 旧版本维护无意义

**Comment by MZZZ-T** [comment]
GOOD

**Comment by Mitpoppy** [comment]
不过我觉得这限制并没有什么 **大的** 用处，因为该想开的照样还是可以开很多，比如霸占列表的EK服和忠贞晓那个服，服务器多到离谱就算限制一个ip两个服，看他们应该有起码3个以上服务器，那么照样3*2=6有6个服务器，我感觉账号系统比较有必要，而不是一味地限制ip可开的服务器，比如有的服务器想开几个mod服，现在mod服非常稀缺，列表我看也就一两个mod服（如果你说是开房间mod完全可以解决，那么很多人并没有那种mod，而有的人要现去群文件或者论坛什么的找，一是公开房有时间限制、二是房主也没耐心）
所以我感觉适当的限制一些普通房而多开一些mod房有必要

**Comment by deng-rui** [comment]
> 不过我觉得这限制并没有什么 **大的** 用处，因为该想开的照样还是可以开很多，比如霸占列表的EK服和忠贞晓那个服，服务器多到离谱就算限制一个ip两个服，看他们应该有起码3个以上服务器，那么照样3*2=6有6个服务器，我感觉账号系统比较有必要，而不是一味地限制ip可开的服务器，比如有的服务器想开几个mod服，现在mod服非常稀缺，列表我看也就一两个mod服（如果你说是开房间mod完全可以解决，那么很多人并没有那种mod，而有的人要现去群文件或者论坛什么的找，一是公开房有时间限制、二是房主也没耐心） 所以我感觉适当的限制一些普通房而多开一些mod房有必要

你们两个打一架罢

**Comment by MZZZ-T** [comment]
> 不过我觉得这限制并没有什么 **大的** 用处，因为该想开的照样还是可以开很多，比如霸占列表的EK服和忠贞晓那个服，服务器多到离谱就算限制一个ip两个服，看他们应该有起码3个以上服务器，那么照样3*2=6有6个服务器，我感觉账号系统比较有必要，而不是一味地限制ip可开的服务器，比如有的服务器想开几个mod服，现在mod服非常稀缺，列表我看也就一两个mod服（如果你说是开房间mod完全可以解决，那么很多人并没有那种mod，而有的人要现去群文件或者论坛什么的找，一是公开房有时间限制、二是房主也没耐心） 所以我感觉适当的限制一些普通房而多开一些mod房有必要

引用秋叶的话：

“没有MOD也进不去房间啊”

那单独开个MOD服有啥用嘞，毕竟大多数玩家未必有那个版本的mod
而且，开6个房间总比开60个房间霸屏好些吧
至于账号系统，那是luke应该去苦恼的事

**Comment by Mitpoppy** [comment]
> > 不过我觉得这限制并没有什么 **大的** 用处，因为该想开的照样还是可以开很多，比如霸占列表的EK服和忠贞晓那个服，服务器多到离谱就算限制一个ip两个服，看他们应该有起码3个以上服务器，那么照样3*2=6有6个服务器，我感觉账号系统比较有必要，而不是一味地限制ip可开的服务器，比如有的服务器想开几个mod服，现在mod服非常稀缺，列表我看也就一两个mod服（如果你说是开房间mod完全可以解决，那么很多人并没有那种mod，而有的人要现去群文件或者论坛什么的找，一是公开房有时间限制、二是房主也没耐心） 所以我感觉适当的限制一些普通房而多开一些mod房有必要
> 
> 引用秋叶的话：
> 
> “没有MOD也进不去房间啊”
> 
> 那单独开个MOD服有啥用嘞，毕竟大多数玩家未必有那个版本的mod 而且，开6个房间总比开60个房间霸屏好些吧 至于账号系统，那是luke应该去苦恼的事

自觉比限制有用，你就算限制到1个服，忠贞晓那种服16个服务器4台机子一台是一个ip那么一样也是4个服务器，限制只能说可以限制那些钱少机少的，但是钱少的他也买不了多少服务器，一样还是上不了多少服务器，有钱人管你限制多少

**Comment by MZZZ-T** [comment]
> > > 不过我觉得这限制并没有什么 **大的** 用处，因为该想开的照样还是可以开很多，比如霸占列表的EK服和忠贞晓那个服，服务器多到离谱就算限制一个ip两个服，看他们应该有起码3个以上服务器，那么照样3*2=6有6个服务器，我感觉账号系统比较有必要，而不是一味地限制ip可开的服务器，比如有的服务器想开几个mod服，现在mod服非常稀缺，列表我看也就一两个mod服（如果你说是开房间mod完全可以解决，那么很多人并没有那种mod，而有的人要现去群文件或者论坛什么的找，一是公开房有时间限制、二是房主也没耐心） 所以我感觉适当的限制一些普通房而多开一些mod房有必要
> > 
> > 
> > 引用秋叶的话：
> > “没有MOD也进不去房间啊”
> > 那单独开个MOD服有啥用嘞，毕竟大多数玩家未必有那个版本的mod 而且，开6个房间总比开60个房间霸屏好些吧 至于账号系统，那是luke应该去苦恼的事
> 
> 自觉比限制有用，你就算限制到1个服，忠贞晓那种服16个服务器4台机子一台是一个ip那么一样也是4个服务器，限制只能说可以限制那些钱少机少的，但是钱少的他也买不了多少服务器，一样还是上不了多少服务器，有钱人管你限制多少

我的观点是这样，这种问题本来就应该是luke管的，他本人也说了考虑限制，但是我们也不能啥都不做
当然我们这边最终还是看dr

**Comment by MZZZ-T** [comment]
> > > > 不过我觉得这限制并没有什么 **大的** 用处，因为该想开的照样还是可以开很多，比如霸占列表的EK服和忠贞晓那个服，服务器多到离谱就算限制一个ip两个服，看他们应该有起码3个以上服务器，那么照样3*2=6有6个服务器，我感觉账号系统比较有必要，而不是一味地限制ip可开的服务器，比如有的服务器想开几个mod服，现在mod服非常稀缺，列表我看也就一两个mod服（如果你说是开房间mod完全可以解决，那么很多人并没有那种mod，而有的人要现去群文件或者论坛什么的找，一是公开房有时间限制、二是房主也没耐心） 所以我感觉适当的限制一些普通房而多开一些mod房有必要
> > > 
> > > 
> > > 引用秋叶的话：
> > > “没有MOD也进不去房间啊”
> > > 那单独开个MOD服有啥用嘞，毕竟大多数玩家未必有那个版本的mod 而且，开6个房间总比开60个房间霸屏好些吧 至于账号系统，那是luke应该去苦恼的事
> > 
> > 
> > 自觉比限制有用，你就算限制到1个服，忠贞晓那种服16个服务器4台机子一台是一个ip那么一样也是4个服务器，限制只能说可以限制那些钱少机少的，但是钱少的他也买不了多少服务器，一样还是上不了多少服务器，有钱人管你限制多少
> 
> 我的观点是这样，这种问题本来就应该是luke管的，他本人也说了考虑限制，但是我们也不能啥都不做 当然我们这边最终还是看dr

当然如果luke比我们先搞出来那更好，就不用苦恼这个问题了

**Comment by deng-rui** [comment]
> > > > > 不过我觉得这限制并没有什么 **大的** 用处，因为该想开的照样还是可以开很多，比如霸占列表的EK服和忠贞晓那个服，服务器多到离谱就算限制一个ip两个服，看他们应该有起码3个以上服务器，那么照样3*2=6有6个服务器，我感觉账号系统比较有必要，而不是一味地限制ip可开的服务器，比如有的服务器想开几个mod服，现在mod服非常稀缺，列表我看也就一两个mod服（如果你说是开房间mod完全可以解决，那么很多人并没有那种mod，而有的人要现去群文件或者论坛什么的找，一是公开房有时间限制、二是房主也没耐心） 所以我感觉适当的限制一些普通房而多开一些mod房有必要
> > > > 
> > > > 
> > > > 引用秋叶的话：
> > > > “没有MOD也进不去房间啊”
> > > > 那单独开个MOD服有啥用嘞，毕竟大多数玩家未必有那个版本的mod 而且，开6个房间总比开60个房间霸屏好些吧 至于账号系统，那是luke应该去苦恼的事
> > > 
> > > 
> > > 自觉比限制有用，你就算限制到1个服，忠贞晓那种服16个服务器4台机子一台是一个ip那么一样也是4个服务器，限制只能说可以限制那些钱少机少的，但是钱少的他也买不了多少服务器，一样还是上不了多少服务器，有钱人管你限制多少
> > 
> > 
> > 我的观点是这样，这种问题本来就应该是luke管的，他本人也说了考虑限制，但是我们也不能啥都不做 当然我们这边最终还是看dr
> 
> 当然如果luke比我们先搞出来那更好，就不用苦恼这个问题了

前端后端谁来写 (
你抓一个罢

**Comment by Mitpoppy** [comment]
> > > > > > 不过我觉得这限制并没有什么 **大的** 用处，因为该想开的照样还是可以开很多，比如霸占列表的EK服和忠贞晓那个服，服务器多到离谱就算限制一个ip两个服，看他们应该有起码3个以上服务器，那么照样3*2=6有6个服务器，我感觉账号系统比较有必要，而不是一味地限制ip可开的服务器，比如有的服务器想开几个mod服，现在mod服非常稀缺，列表我看也就一两个mod服（如果你说是开房间mod完全可以解决，那么很多人并没有那种mod，而有的人要现去群文件或者论坛什么的找，一是公开房有时间限制、二是房主也没耐心） 所以我感觉适当的限制一些普通房而多开一些mod房有必要
> > > > > 
> > > > > 
> > > > > 引用秋叶的话：
> > > > > “没有MOD也进不去房间啊”
> > > > > 那单独开个MOD服有啥用嘞，毕竟大多数玩家未必有那个版本的mod 而且，开6个房间总比开60个房间霸屏好些吧 至于账号系统，那是luke应该去苦恼的事
> > > > 
> > > > 
> > > > 自觉比限制有用，你就算限制到1个服，忠贞晓那种服16个服务器4台机子一台是一个ip那么一样也是4个服务器，限制只能说可以限制那些钱少机少的，但是钱少的他也买不了多少服务器，一样还是上不了多少服务器，有钱人管你限制多少
> > > 
> > > 
> > > 我的观点是这样，这种问题本来就应该是luke管的，他本人也说了考虑限制，但是我们也不能啥都不做 当然我们这边最终还是看dr
> > 
> > 当然如果luke比我们先搞出来那更好，就不用苦恼这个问题了
> 
> 前端后端谁来写 (
> 你抓一个罢

前端：dr
后端：dr
RW开发：dr
api开发：dr
游戏开发： ~~luke~~ （dr）

**Comment by deng-rui** [comment]
@Mitpoppy 扬了 就你了

**Comment by Mitpoppy** [comment]
> @Mitpoppy 扬了 就你了

阿这（离了个大谱）

**Comment by deng-rui** [comment]
放弃

**Comment by Mitpoppy** [comment]
> 放弃

简称咕了🌚
