### ISSUE TITLE
[手动更新] 使用增量更新

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#246]
**功能介绍：**
服务端可以支持自动更新到发布的正式最新版本，可以免去用户手动更新的麻烦，可以调用github api实现自动更新
**赞助支持**
本功能可以作为收入的来源之一，比如购买自动更新服务，比如以下方式：
- 按月购买，一个月内所有的版本包更新
- 按次数购买，多少钱可以买多少次自动更新
- 永久，多少钱买一次可以永久使用自动更新
（推荐购买系统不开源）

**Comment by deng-rui** [comment]
> **功能介绍：** 服务端可以支持自动更新到发布的正式最新版本，可以免去用户手动更新的麻烦，可以调用github api实现自动更新 **赞助支持** 本功能可以作为收入的来源之一，比如购买自动更新服务，比如以下方式：
> 
> * 按月购买，一个月内所有的版本包更新
> * 按次数购买，多少钱可以买多少次自动更新
> * 永久，多少钱买一次可以永久使用自动更新
>   （推荐购买系统不开源）

自动更新避免了手动去获取jar 同时 RW-HPS也有一套成熟的更新方案 (指 SFE 2.0没使用的)

但是对于付费服务 我并不认同
理由如下 :
- 已经许诺过 : **赞助是全自愿的。赞助者不会获得特权，不赞助也可以使用全部的功能**
-  我本人也不认同这种方式
- (也没人会给钱 超小声)

**Comment by Mitpoppy** [comment]
> > **功能介绍：** 服务端可以支持自动更新到发布的正式最新版本，可以免去用户手动更新的麻烦，可以调用github api实现自动更新 **赞助支持** 本功能可以作为收入的来源之一，比如购买自动更新服务，比如以下方式：
> > 
> > * 按月购买，一个月内所有的版本包更新
> > * 按次数购买，多少钱可以买多少次自动更新
> > * 永久，多少钱买一次可以永久使用自动更新
> >   （推荐购买系统不开源）
> 
> 自动更新避免了手动去获取jar 同时 RW-HPS也有一套成熟的更新方案 (指 SFE 2.0没使用的)
> 
> 但是对于付费服务 我并不认同
> 理由如下 :
> - 已经许诺过 : **赞助是全自愿的。赞助者不会获得特权，不赞助也可以使用全部的功能**
> -  我本人也不认同这种方式
> - (也没人会给钱 超小声)

不过我赞同用github因为需要科学上网。。。
赞助的话。。可是没有收入来源全靠情怀嘛

**Comment by deng-rui** [comment]
> > > **功能介绍：** 服务端可以支持自动更新到发布的正式最新版本，可以免去用户手动更新的麻烦，可以调用github api实现自动更新 **赞助支持** 本功能可以作为收入的来源之一，比如购买自动更新服务，比如以下方式：
> > > 
> > > * 按月购买，一个月内所有的版本包更新
> > > * 按次数购买，多少钱可以买多少次自动更新
> > > * 永久，多少钱买一次可以永久使用自动更新
> > >   （推荐购买系统不开源）
> > 
> > 
> > 自动更新避免了手动去获取jar 同时 RW-HPS也有一套成熟的更新方案 (指 SFE 2.0没使用的)
> > 但是对于付费服务 我并不认同
> > 理由如下 :
> > 
> > * 已经许诺过 : **赞助是全自愿的。赞助者不会获得特权，不赞助也可以使用全部的功能**
> > * 我本人也不认同这种方式
> > * (也没人会给钱 超小声)
> 
> 我确实也不赞同用github因为需要科学上网。。。 赞助的话。。可是没有收入来源全靠情怀嘛

情怀(确信)
![image](https://user-images.githubusercontent.com/39623218/179386794-657d09c7-b3d6-44a1-a1dc-52a6fd5d1f1f.png)

**Comment by wihn2021** [comment]
能用为啥要更新

**Comment by Mitpoppy** [comment]
> 能用为啥要更新

emmm单纯是提出想法，别的没考虑233

**Comment by deng-rui** [comment]
> 能用为啥要更新

可选更新?

**Comment by Mitpoppy** [comment]
> > 能用为啥要更新
> 
> 可选更新?

可选更新，那和输命令才自动更新（的手动更新）没啥区别

**Comment by deng-rui** [comment]
> > > 能用为啥要更新
> > 
> > 
> > 可选更新?
> 
> 可选更新，那和输命令才自动更新（的手动更新）没啥区别

要不? 咕咕咕

**Comment by deng-rui** [comment]
新增命令
[.updataserver]

**Comment by deng-rui** [comment]
需要等待具有可下载的正式版后方可进行测试并加入
API: https://api.github.com/repos/RW-HPS/RW-HPS/releases/latest
