### ISSUE TITLE
Display server info after receiving a packet of a specific type

### ISSUE THREAD

**Issue by wihn2021** [RW-HPS/RW-HPS#249]
RW-HPS has had strategies while receiving typical types of network packets, which are used in Rusted Warfare. They are related to the game. However, it is necessary to develop another system of packets to control the server, or at least, get some information about the server. I know net APIs, but they are too complex and heavy compared to just TCP packets of the types that the game has not used. For example, by receiving a packet of type 12345, the server should return the number of players in game.

**Comment by wihn2021** [comment]
Thus, it would be easier to gather infomation or to control the server, by accepting and sending binary packets.

**Comment by deng-rui** [comment]
There are already methods for this problem

You can use the PACKET_DEBUG(TYPE-2000)package
The server returns the message TYPE-2001
You can find this in the AbsNet section

I will add a custom registration Packet protocol later on

**Comment by deng-rui** [comment]
If it accepts a GetServerInfoPacket to return ServerInfo, as Mc and Mindustry do, then these will be added later

**Comment by deng-rui** [comment]
PACKET Send :
Type : 3000 Length : 4 Data: Hi


SERVER Result : 
Type : 3001 Length : * 
Data:
```
if (SERVER) {
ServerProtocol

Player.size
MaxPlayer

MapName

income
credits
noNukes
initUnit
mist
sharedControl
}
```

```
if (RELAY) {
RelayProtocol / RelayMulticastProtocol
RELAYPlayer.size
Room.size

// There may be more
}
```
