### ISSUE TITLE
为聊天机器人添加专用接口

### ISSUE THREAD

**Issue by MZZZ-T** [RW-HPS/RW-HPS#254]
比如，在一个QQ群内，群员向QQ机器人发送消息，机器人向RW-HPS的接口发送指定的信息，RW-HPS开一个空房间等待玩家进入，或者机器人通过接口获取服务器当前的信息什么的

**Comment by deng-rui** [comment]
Link #249

**Comment by Mitpoppy** [comment]
我感觉也可以发过来比如实现游戏内聊天发到QQ群内（用命令，可以大程度减少刷屏）

**Comment by deng-rui** [comment]
- [ ] 新的依赖需求 Mirai
- [ ] 新的 Lib 管理器

**Comment by 493505110** [comment]
直接把lib打包进jar是不是就不需要管理器了(

**Comment by 493505110** [comment]
直接把lib打包进jar是不是就不需要管理器了(

**Comment by deng-rui** [comment]
> 直接把lib打包进jar是不是就不需要管理器了(

依赖重复直接炸死你

**Comment by JoeLeaf** [comment]
可以提供http或者websocket正向反向,用来直接执行命令和信息同步接口挺不错,实现也不麻烦

**Comment by deng-rui** [comment]
> 可以提供http或者websocket正向反向,用来直接执行命令和信息同步接口挺不错,实现也不麻烦

HTTP/HTTPS/WS/WSS正在做 (

**Comment by deng-rui** [comment]
但缺一个较好的 API 格式/文档
