### ISSUE TITLE
提供状态查询api接口

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#257]
跪求服务器状态查询api接口
具体需要内容：
- 服务器名称
- 服务器ip:port
- 服务器开关状态
- 服务器在线人数/总人数
- 服务器是否已经开始游戏
- 服务器已经开始游戏的游玩时间
- 服务器已运行时间
- 服务器开启时间
- 服务器所使用的地图名：xxx
- 服务器所使用的mod列表：xxx
- 服务器所开启的插件列表：xxx
- 服务器是否开放端口进去
- 服务器是否上线多人游戏列表
- 该ip下有多少个服务器正在运行

**Comment by deng-rui** [comment]
最后一个不应该由服务器返回

**Comment by Mitpoppy** [comment]
> 最后一个不应该由服务器返回

不能通过扫描ip获得嘛

**Comment by deng-rui** [comment]
> > 最后一个不应该由服务器返回
> 
> 不能通过扫描ip获得嘛

自己去nmap 服务器实现这个存在歧义
FRP 哭泣

**Comment by Mitpoppy** [comment]
> > > 最后一个不应该由服务器返回
> > 
> > 不能通过扫描ip获得嘛
> 
> 自己去nmap 服务器实现这个存在歧义
> FRP 哭泣

阿这，不慌反正用处不大，把启动器的开启服务器数量扣了就行了（｡ò ∀ ó｡）（不过好像能通过本地检测命令提示符实现）

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/185636643-dd31d7ee-4f6a-4141-b446-2d10c986d60b.png)
要的是这种效果吗，等我完善一下再pr（

**Comment by Mitpoppy** [comment]
> ![image](https://user-images.githubusercontent.com/29498336/185636643-dd31d7ee-4f6a-4141-b446-2d10c986d60b.png)
> 要的是这种效果吗，等我完善一下再pr（

哇，这种效果完美（｡ò ∀ ó｡）

**Comment by 493505110** [comment]
#272

**Comment by Mitpoppy** [comment]
> #272 

我看你说明的配置文件
```
{"enabled":true,"listen":"127.0.0.1","port":8080,"token":"defaultToken"}
```
是不是直接默认使用8080端口作为httpapi接口，但是我感觉这样的方式对nat服务器或者面板服并不怎么友好，因为像面板服，他只能使用一个端口，所以我建议是默认使用服务器开服的端口，共用一个端口后比较方便

**Comment by 493505110** [comment]
前面的共用端口可以实现，不过后面的我能力不足（

**Comment by Mitpoppy** [comment]
> 前面的共用端口可以实现，不过后面的我能力不足（
> 应该要模拟客户端才能吧

阿这，好吧，不过还是感谢提供接口

**Comment by 493505110** [comment]
哦对了，忘了告诉你了，前面的已经实现了
