### ISSUE TITLE
『新的模式』排位赛

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#258]
**新的玩法：排位模式**
# 前述
"可能"有大部分游戏都有，比如王者农药、cf、吃dr（j）、球球大作战等众多游戏都有的功能"排位"，顾名思义就是在游戏内有普通模式和排位模式之分，而排位模式有段位（比如dr输了就把他女盆友扔了这件事），并且比较正式，然后就是还有排行榜，和赛季，可以让玩家更有挑战。
当然都是在游戏底层代码实现（luke的活），但是！我想dr这个漂亮大方可爱的人，应该会去试试在服务器层面实现🙃。
# 具体内容
- 排位赛制模式
- 可以通过比赛来提高段位（具体段位dr想想🙃），参考王者农药，赢一次加一个星星，然后进阶套娃段位制，输一次掉星星
- 开始比赛时可以禁用 ~~英雄~~ （单位）
- 可分为团队赛和个人挑战赛
- 原版/自定义游戏地图随机匹配
- 可由 超级管理员/服务器管理员/某一位漂亮 落落大方的dr 来设置奖励或者奖金
# 排行榜
- 基于游戏内的排行榜dr实现可能只能在聊天界面输入命令，回复排行榜文字了吧
- 如果可以的话我感觉也可以在网页端实现美化版的排行榜（推荐mdui框架）
# 重大问题
具体有一个事情。。。那就是。。好像没有账号系统，所以。。。真的完成不了的吗（｡ò ∀ ó｡）
 **不** ，应该还有其他办法，可以试试每个独立服务器串通起来，然后组成一个排位体系，账号。。。可以用密钥实现，加入 **排位赛** 游戏时输入密钥经过后天核对后加入（纯属放屁）
rcn那种服务器感觉容易实现（好像我还在放屁）

**Comment by deng-rui** [comment]
看起来没有好办法

因为 不存在模拟层

**Comment by Mitpoppy** [comment]
> 看起来没有好办法
> 
> 因为 不存在模拟层

所以你tm模拟层啥时候好

**Comment by deng-rui** [comment]
> > 看起来没有好办法
> > 因为 不存在模拟层
> 
> 所以你tm模拟层啥时候好

等 鸡啄完米 狗舔完面

**Comment by Mitpoppy** [comment]
> > > 看起来没有好办法
> > > 因为 不存在模拟层
> > 
> > 所以你tm模拟层啥时候好
> 
> 等 鸡啄完米 狗舔完面

我明白了，dr=狗+鸡！

**Comment by deng-rui** [comment]
借助于 RCN 的绑定系统
我们将很快实现此功能

RCN Team.

**Comment by WITpakchoi** [comment]
我很期待
