### ISSUE TITLE
『新的模式』BOSS战

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#259]
# 介绍
多名玩家开始游戏，随机或房主指定某个玩家A1成为BOSS（也可以是再加个boss的小跟班A2），然后其他玩家成为 **好人**  ~~（dr是坏人）~~ 
# 玩法
玩家每个人控制一个具体单位（可以是实验单位或者什么可以移动的单位）
然后boss单位属性比较多、血量超多！，并且可以主动进攻
但是玩家可以放置单位（一段时间自动给一个随机单位放置机会）来防御boss
这样比较考验玩家团队合作
 ~~（具体其他玩法dr看着做😽）~~

**Comment by deng-rui** [comment]
看起来可以实现 但我需要更多数据来进行测试

依赖 PACKET-SYNC

**Comment by Mitpoppy** [comment]
> 看起来可以实现 但我需要更多数据来进行测试
> 
> 依赖 PACKET-SYNC

这几个玩法我看很多地图实现的，我感觉你可以去找找地图参考一下

**Comment by deng-rui** [comment]
我的想法是 :

PLAYER 分两份


BOSS 是一个人 拿着厚血单位 漫天跑 拥有秒建( 只能建建筑 不能生产
其他玩家 防御boss(可以生产单位

**Comment by Mitpoppy** [comment]
> 我的想法是 :
> 
> PLAYER 分两份
> 
> 
> BOSS 是一个人 拿着厚血单位 漫天跑 拥有秒建( 只能建建筑 不能生产
> 其他玩家 防御boss(可以生产单位

但是你有没有考虑过如果Boss比玩家跑得快呢。。。

**Comment by 1838601405** [comment]
这个想法不如我的moba模式

**Comment by 1838601405** [comment]
> 

我们黑森mod已经做了一些了

**Comment by Mitpoppy** [comment]
> 这个想法不如我的moba模式
> 

毕竟是在服务端层面考虑，限制太大，我也只是单纯提供想法，真正主力还是你们🤣
