### ISSUE TITLE
『新的模式』攻防模式

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#260]
# 介绍
- 前情提要：分为好人方和坏人方 ~~（dr是坏人）~~ ，好人方防御，坏人方攻击

 **防守模式** 
- 防守方：玩家可以通过建筑/生成单位来防御敌人攻击（或主动攻击）来取得胜利，或者等到时间结束并且好人方有建筑单位存留那么好人方面获得胜利！
- 攻击方：有两名/一名玩家担任攻击方坏人角色，防御方开始时防御方有一段时间建筑/生成单位（期间攻击方不能攻击）
等时间限制结束后（可以是上面显示倒计时，我看有的地图屏幕上面可以调用游戏原版功能显示文字），攻击方开始攻击防御方，但是不能自己建筑单位/建筑（可以给攻击方0元并且不给加钱），只能是系统给攻击方的玩家生成单位
 **辅助玩家** 
然后开头说可以有两名玩家，那么A2是辅助攻击方的坏人， **辅助玩家** 不能控制主攻击玩家单位（当然也可以选择可以控制，可选），系统也会给辅助玩家生成部分小（多）单位来辅助主玩家攻击
# bug问题
- 空军可能会导致游戏有点不平衡，可以考虑禁止建筑空军基地
- 攻击方玩家可能会存大量单位导致游戏卡，当然防御方也可能会生成一群单位
- 地图问题，如果玩家随便选择地图，可能会导致本来的玩法被改变，可以试试固定几张地图选择

**Comment by deng-rui** [comment]
显示时间是tmx的范畴了

服务端无解

**Comment by Mitpoppy** [comment]
> 显示时间是tmx的范畴了
> 
> 服务端无解

可以是这个玩法对应只能使用某个地图，然后地图早固定好玩法模式
