### ISSUE TITLE
加入房间后显示已过聊天消息

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#261]
# 起因
有时候加入游戏后，他们在聊规则或者什么的，但是自己加入的比较晚，然后看不到上面的消息，就导致自己和他们格格不入（｡ò ∀ ó｡），经过一会时间才了解他们具体说的什么，我不知道这个消息是游戏支持，还是服务端支持所以。。提一下
# 功能介绍
房间已开一段时间，然后后来的玩家加入后可以看见之前聊的好几条消息（固定显示几条消息｜或者根据时间，显示几分钟/秒前发的消息）
如果感觉这样比较挡进入时自动发的服务器消息的话，可以考虑用改成输入命令显示消息

**Comment by deng-rui** [comment]
## 命令(客户端):
固定这个消息 (最多五个)
.pin id 消息
删除指定id消息:
.rmpin id
