### ISSUE TITLE
一服多房机制（类似小明的服）

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#262]
# 介绍
在铁锈战争多人联机那里看见小明的服务器是一服多房间，比较想实现
注意这里说的一服多房间，不是："relay的那种一个服务器内然后开一个房间，这个房间再独立出来成一个类似独立服务器的房间"
# 概念
这里指的一服多房机制是依靠一个服务器，也就是开一个独立的"类似"relay的服务器，然后这个服务器在列表显示是有两个属性：玩家总人数和房间数量（就是在列表最上方不是有个服务器名称、地图名称、玩家人数什么的，在那个列表上再加个房间数量，这个建议后期Dr可以考虑和luke沟通一下加上，或者是如果是dr实现的可以加一下）

## 具体如何实现

具体这个 **"独立的类似relay服务器的一服多房的服务器，后面简称幻想服务器"** 实现原理，就是服主在云服务器上上传一个幻想服务器，然后在多人游戏列表显示的是一个独立服务器

没错到这里和正常的RW服务器差不多，但是看到后面

虽然显示的是一个独立服务器，但是前面显示的玩家总人数和房间数量可和其他服务器不一样
### 逻辑
这个服务器进去一个新玩家A1如果服务器内没有缺人的房间，那么自动为该玩家创建一个新房间B1，后续如果下一个新玩家A2再进来检测到有缺人的房间B1，那么这个玩家自动加入到这个房间内，后面A3456循环这样
### 房间显示
并且这个房间并不会显示到多人游戏的列表内，而只是存在在这个服务器内。
### relay服务器
这样我感觉类似私人开的relay服务器，不上传列表但能创建多个房间，但是缺点不能自动分配到缺人的房间，并且占用列表位置比较多，毕竟一个房间等于一个独立服务器（但是这种情况只是存在在RCN等官服，因为有IP开服数量限制，普通服主开不了那么多上列表的服务器）。relay服务器有缺点也有优点，优点是玩家可以自由的选择服务器，自由度比较大，可以直接看见房间名字。
# 一些想法
我感觉"幻想服务器"虽然可以让服主们实现一个端口开很多个服务器，但是也有一些Dr蛋疼（哦，Dr是女生没蛋）的问题，比如选择上，玩家只能任由服务器分配房间，而不能自己选择要进入的房间。所以这样的服务器比较适合于玩法比较固定的，比如之前实现的天选模式、不限建筑速度模式。当然也并不是说其他的普通玩法就不能用了，只是比较适合。
如果这样的机制可以和relay一样可以让玩家自己使用自己的mod和地图那就好了，而不是独立服务器那样只能使用云服务器上提前安装好的，这样局限性太大。
## 一些想法待讨论
- 这种一服多房机制如果好！那么会把限制IP开服数量变成1个吗
- 这种一服多房机制可以考虑和RCN这样的服务器共存（具体没什么想法）
-  **重要！！** 基于幻想服务器的情况下是否可以考虑，每个服务器都可以是一个列表，也就是进去一个私人服务器后，会打开一个这个群组服务器专门的列表，这个列表内只显示这个私人服务器内的房间，和之前聊的一个独立服务器做中转，然后可以通过命令去其他独立服务器差不多
- 由于RW-HPS服务端是开源的，那么会不会出现 **违法、色q、db** 改变服务端开服源文件，而服务器内房间又不像RCN那样暴露，导致替在的危害

**Comment by deng-rui** [comment]
需要进行更多讨论以确定细节

**Comment by deadmau5v** [comment]
很好的想法

**Comment by 493505110** [comment]
是否可以参照relay,加入游戏时遍历所有relay,玩家分配到未满员的房间中,若全都满员则创建一个relay房间

**Comment by deng-rui** [comment]
> 是否可以参照relay,加入游戏时遍历所有relay,玩家分配到未满员的房间中,若全都满员则创建一个relay房间

不理智
不应该直接创建
应该设置MaxRoomSize

**Comment by Mitpoppy** [comment]
> > 是否可以参照relay,加入游戏时遍历所有relay,玩家分配到未满员的房间中,若全都满员则创建一个relay房间
> 
> 不理智
> 不应该直接创建
> 应该设置MaxRoomSize
> 
> 遍历或许是好选择
> 按照顺序寻找即将满员房间

如果房间比较多遍历会不会比较浪费时间，或者废性能

**Comment by wihn2021** [comment]
> 

不用遍历，每时每刻仅有一个【未满员房间】，所有人加进去即可，等到它变成了【满员房间】，则创建又一个新的空房间。

**Comment by deng-rui** [comment]
> > 
> 
> 不用遍历，每时每刻仅有一个【未满员房间】，所有人加进去即可，等到它变成了【满员房间】，则创建又一个新的空房间。

List是罢

**Comment by Mitpoppy** [comment]
> > > 
> > 
> > 不用遍历，每时每刻仅有一个【未满员房间】，所有人加进去即可，等到它变成了【满员房间】，则创建又一个新的空房间。
> 
> List是罢

可以是已开启的房间为1，未开启的房间为0，然后只遍历未开启的房间

**Comment by deng-rui** [comment]
意义不大
RELAY足够
