### ISSUE TITLE
『新的模式』躲猫猫

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#264]
# 介绍
躲猫猫模式不同于之前几个大概率需要固定地图的模式（当然也可以选择固定开发的地图，不过这样自由度会削弱）
## 一般的躲猫猫规则
躲猫猫模式，玩过其他躲猫猫游戏的应该都知道，玩家可以躲在一个地方而不被发现，然后随机一个抓捕者去抓，如果抓到，那么被抓的就会变成抓捕者，依次循环
# 铁锈战争躲猫猫
如果在铁锈战争里实现躲猫猫的话，毕竟单位和场景格格不入，我感觉可以参考我的世界小游戏服的躲猫猫。
## 具体规则
 **进入游戏前** 玩家随机/固定（不建议固定因为有老6， ~~比如dr~~ ）选出一名玩家来当抓捕者
然后其他玩家当躲的，躲的玩家可以变成任何场景中的单位/物品/建筑
### 技能
 **抓捕者技能** 

- 神奇飞蛋 玩家可以发射远程飞蛋来攻击躲的，并且有减速效果
-  **注意** 玩家发动普通攻击会减少生命值，生命值不可恢复，除非打中真正的躲藏的玩家，才可以不减血并且恢复部分生命值。

 **逃脱者技能** 

> 游戏刚开始时的阶段
> > 开始时玩家技能只有一个，技能是
> > 让玩家变成其他单位/建筑/物品，我觉得可以把沙盒模式的单位直接搬过来，然后属性全部下降，毕竟如果他选择不符合场景的，立马会被看见

游戏开始后的阶段
- 固定位置 逃脱者玩家右边可以有个技能就是固定玩家所在的单位位置，有可能会误触导致单位移动
- 加速移动 技能2可以让玩家加速一段时间，类似游戏内某个可以加速的激光飞机（忘记名字了）
- 小爆炸 技能3玩家可以释放一个和烟花差不多的没有任何伤害的小爆炸，来装x（像极了Dr装x的时候）

**Comment by deng-rui** [comment]
建筑无法移动 综上所述 并没有什么好方法
