### ISSUE TITLE
游戏中重连导致炸服『BUG』

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#265]
## 简单说一下BUG
游戏开始后，如果有玩家退出或者退出的玩家重连，大概率会导致本来在游戏中正常的玩家出现同步游戏中，并且这个画面是黑屏状态的
有时候会影响比较大比如我正在进攻你特么给我来一下
或者有时候就是直接导致玩家一直在同步中然后一直黑屏，只能退出游戏重新进
或者再有的时候，就是之前反馈过的bug，游戏中一直循环同步游戏中，导致玩一会就重置游戏回档，很恶心。。。

**Comment by deng-rui** [comment]
已解决

目前使用可信内部 Game-Lib.jar 来生成同步包
