### ISSUE TITLE
linux中开启服务器后设置语言再次重启服务器无效『BUG』

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#266]
# 简介
系统：ubuntu
cpu框架：amd64
启动服务器后默认语言英文，输入命令设置语言中文后，重启服务器，后发现依然是英文

**Comment by deng-rui** [comment]
用了什么命令

我无法复现

**Comment by Mitpoppy** [comment]
> 用了什么命令
> 
> 我无法复现


就是setlang什么的那个切换语言命令，我切换中文后重启游戏服务器，还是英文

**Comment by deng-rui** [comment]
重输入试试
正常情况下 语言改变 会提示一句话的

**Comment by deng-rui** [comment]
草 忘记持久化了
