### ISSUE TITLE
铁锈游戏服务器环境差到离谱

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#267]
游戏内个别服务器服主，因私人恩怨，服务器名称改为骂人、骂祖宗等名称，希望调整服务器环境，并且加入屏蔽词等功能
![Screenshot_2022-08-19-12-23-21-08_8631dd15e8465f7b557741726434b4fd.jpg](https://user-images.githubusercontent.com/89001400/185543147-0a71bcb3-5ce3-464c-9516-0c9430e023d2.jpg)

**Comment by deng-rui** [comment]
![image](https://user-images.githubusercontent.com/39623218/185549775-686be253-452a-48c1-9752-4600530c054a.png)
