### ISSUE TITLE
为 RELAY 房间加入 投票关闭

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#275]
# 功能介绍
玩家可以通过指令/GUI来举报某个玩家，通过后台审核是否有违规行为，并且做出相应处罚措施
# 一些问题
- 由于铁锈战争现阶段没有账号系统，所以就导致举报玩家只能单纯获取到玩家手机序列号、IP地址、玩家名称等，封名称的话玩家可以改名，当然封ip是可采取的，但是家里宽带路由器是重启可以改变ip地址的，所以就导致举报变成了一个很繁琐的事情
- 玩家如果用脚本大量发送举报数据，如何来辨别
- 玩家恶意发送举报信息
- 后台如何查询玩家是否有违规行为
# 想法
- 独立服务器或者私人的relay服务器能否可以把封ip，与RCN或者官服的ip封禁列表云同步
- 玩家如果知道自己错了，想后悔，那么解封途径应该怎么设定，我建议是在游戏内添加链接提交解封或者用网页的方式提交后台，并且收取一定费用，提高解封门槛，才会让玩家怕被封
- 规则条款，话说条款这东西是不是luke要做的，不过还是提一下吧，在游戏中醒目位置添加条款约束玩家行为
### 自言
- 我觉得举报功能不止于此，首先他可以让服务器管理者更快的知道问题或者违规的发生，而不至于像之前利用RCNUP功能骂人的那样发生比较长的一段时间，才通过玩家反馈得到消息

**Comment by 493505110** [comment]
> 并且收取一定费用

**Comment by deadmau5v** [comment]
解封还要费用？

**Comment by deng-rui** [comment]
解封还要费用？

**Comment by deng-rui** [comment]
https://github.com/RW-HPS/RW-HPS#sponsorship
全文背诵

**Comment by Mitpoppy** [comment]
> 解封还要费用？

emmm不是，我是写的可选项目。。。
解封正常申诉后解封也没啥问题

**Comment by deng-rui** [comment]
RELAY :
.kr
kill room
当房间投票达到 70 % 即关闭房间并拉黑一段时间
