### ISSUE TITLE
希望提供一个锁定混战的功能

### ISSUE THREAD

**Issue by deadmau5v** [RW-HPS/RW-HPS#280]
我经常玩一些混战图 但需要每一把游戏开局前手动调到混战模式
希望添加一个和 maplock 类似的命令 可以在后台或者Config里锁定游戏为混战模式

**Comment by 493505110** [comment]
貌似有个未使用的类`GameVersionFFA`可以解决这个问题?

**Comment by 493505110** [comment]
#281

**Comment by deng-rui** [comment]
Server Command :
dogfightlock
