### ISSUE TITLE
『新的命令』控制台切换大厅地图

### ISSUE THREAD

**Issue by deadmau5v** [RW-HPS/RW-HPS#286]
# 介绍
为RW-HPS添加一个在控制台切换大厅地图的命令
方便服务器重启后快速设置地图

# 具体功能
功能类似于房主的.map命令
map + 地图编号 来切换地图
控制台切换地图可以绕过maplock

**Comment by deng-rui** [comment]
修改 changemap
使其兼容 热修改 或 冷修改

Command :
changemap MapsName Boolean
