### ISSUE TITLE
MOD服务器过一段时间无法正常游戏

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#291]
bug实测：幻想天域三服升级MOD服（到8.29号现依然存在bug）（可以到列表去试一下）
1.15和1.14版本均存在问题，服务器内玩家0人，服务器显示没开（包括后台也是），但是玩家进入显示已经开启游戏
### bug还原
服务器开一段时间后会出现如上情况，我这里是4个服只有MOD服有问题，版本：1.14，其他服务器均正常
我这里因为服务器续费两年，所以一直开着没动过，出问题具体什么原因我感觉应该和mod加载机制有关，但是不排除可能是设置问题或者普通服也可能存在
所用MOD：升级5.0
### 解决方法
现在只能是靠重启服务器解决，望修复

**Comment by deng-rui** [comment]
没任何报错?
RW-HPS版本是?
Config.Log 改成 INFO 然后复现看看

**Comment by Mitpoppy** [comment]
> 没任何报错?
> RW-HPS版本是?
> Config.Log 改成 INFO 然后复现看看

版本：6.0.0
重启了暂时没发生
