### ISSUE TITLE
转移房主权限显示消息错误问题

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#297]
在房间内（未开始游戏时）如果手动give他人房主权限，转移没问题，但是消息却显示玩家A将房主转移给了玩家A，而不是显示玩家B
![Screenshot_2022-08-31-19-42-28-94_8631dd15e8465f7b557741726434b4fd.jpg](https://user-images.githubusercontent.com/89001400/187712713-a2efbff7-c4bd-4088-bf71-bcdbee739249.jpg)

**Comment by 493505110** [comment]
#299
