### ISSUE TITLE
同步错误

### ISSUE THREAD

**Issue by mizukiforever** [RW-HPS/RW-HPS#300]
6.4.0 server模式开服，开始一分钟后提示 正在同步，等待30-60秒 然后卡死
Log截图：
![)`G_)_`W6(ROJK)TW4)O AT](https://user-images.githubusercontent.com/107687649/188259229-3b4200dd-070a-4c7a-ad2a-1f67873b7b2b.png)

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/188262421-ef8ab49c-dd92-461a-ae5a-ffbad2602f3c.png)
貌似是客户端的问题，服务端设计的似乎是检测到这段文本就sync

**Comment by deng-rui** [comment]
#221
目前没什么解决办法
等我抽时间看看1.15动了什么东西

**Comment by deng-rui** [comment]
错误原因（可能）
因为玩家版本不同步
RW-HPS 并没有验证玩家版本同步性

**Comment by deng-rui** [comment]
已解决

目前使用可信内部 Game-Lib.jar 来生成同步包
