### ISSUE TITLE
Relay类型服务器无法使用手动同步命令

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#302]
Relay类型服务器无法使用手动同步命令，在服务器内开的房间包括RCN房间都没有发现有手动同步命令，我记得dr说过是.sy什么的命令，使用后无效，help帮助也没有说明，正常独立服务器可以使用该命令，望修复
### 玩家
玩家可以个人手动输入命令同步游戏服务器，只单纯同步输入玩家的个人
### 房主
房主输入同步命令后同步全部玩家游戏画面

**Comment by 493505110** [comment]
relay协议应该是只负责转发，不能控制



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月10日(周六) 晚上8:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [RW-HPS/RW-HPS] Relay类型服务器无法使用手动同步命令 (Issue #302)




 
Relay类型服务器无法使用手动同步命令，在服务器内开的房间包括RCN房间都没有发现有手动同步命令，我记得dr说过是.sy什么的命令，使用后无效，help帮助也没有说明，正常独立服务器可以使用该命令，望修复
 
手动同步优化思路
 
玩家
 
玩家可以个人手动输入命令同步游戏服务器，只单纯同步输入玩家的个人
 
房主
 
房主输入同步命令后同步全部玩家游戏画面

**Comment by deng-rui** [comment]
RELAY不需要任何主动同步
依靠原版即可

**Comment by Mitpoppy** [comment]
> RELAY不需要任何主动同步
> 依靠原版即可

有时候玩生存地图会有延迟不同步现象
