### ISSUE TITLE
房主退出后托管服务器

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#317]
房主如果因为某些原因（比如自退、卡退、闪退等）而导致房间停止运行，导致其他玩家无法进行游戏（俗称房主玩不起， ~~就像dr~~ ）
而我的想法是房主退出之后，该房间会自动由服务器进行托管，玩家可无缝正常游戏，这样可以在实现的基础上减小服务器压力，并且让玩家玩♂ ~~dr~~ 的舒心

**Comment by deng-rui** [comment]
目前就是这样?
要是 RELAY 那问题不大
目前实现非常简单

**Comment by deng-rui** [comment]
但我没时间
可能下个月罢

**Comment by Mitpoppy** [comment]
> 但我没时间
> 可能下个月罢

我还等着你模拟层呢，哈哈

**Comment by deng-rui** [comment]
> > 但我没时间
> > 可能下个月罢
> 
> 我还等着你模拟层呢，哈哈

模拟层已经有了

**Comment by Mitpoppy** [comment]
> > > 但我没时间
> > > 可能下个月罢
> > 
> > 我还等着你模拟层呢，哈哈
> 
> 模拟层已经有了

好家伙，效率还挺快

**Comment by deng-rui** [comment]
等思路
目前直接用模块Hess加入RELAY是可行的
但是稳定性不知道

等佬去写
