### ISSUE TITLE
房间内错误日志

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#319]
在房间内一直不定时显示报错，具体如下：
```
错误，请重新输入或报告开发者:java.io.FileNotFoundException: /storage/emulated/0/rustedWarfare/Blacklist.json: open failed: EACCES (Permission denied)
```
![Screenshot_2022-11-04-20-38-08-20_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/89001400/199974489-9680f07d-fe0c-40c7-b842-f6fe2e19fcd7.jpg)

**Comment by deng-rui** [comment]
干了什么

**Comment by Mitpoppy** [comment]
> 干了什么

我也不清楚，我进了一个房间，然后聊天那里一直提示报错，并且游戏出现卡顿

**Comment by deng-rui** [comment]
看起来，像指令版？

**Comment by Mitpoppy** [comment]
> 看起来，像指令版？

这。。看着好像是房主那边的问题唉，存储目录显示都是手机目录
