### ISSUE TITLE
服务器开始游戏后所有队伍全是绿色

### ISSUE THREAD

**Issue by npldys** [RW-HPS/RW-HPS#335]
开始游戏后服务器内所有玩家的位置都是绿色，即时退出重新连接服务器进入后位置依然是绿色

**Comment by deng-rui** [comment]
这个需要一个正常的例子和反面做对比

**Comment by deng-rui** [comment]
我不清楚是否是右上角的地图

**Comment by npldys** [comment]
正常情况应该是这种
![Screenshot_20221216_130224](https://user-images.githubusercontent.com/118544146/208026245-b055c017-7488-499e-b493-bd76664f10eb.jpg)
![Screenshot_20221216_130228](https://user-images.githubusercontent.com/118544146/208026273-8eaf4fbe-e1d7-4af5-8f8a-967290c2867d.jpg)

**Comment by deng-rui** [comment]
这个问题我想我知道了
