### ISSUE TITLE
加载rwmod文件

### ISSUE THREAD

**Issue by deng-rui** [RW-HPS/RW-HPS#34]
Packet : NULL
Info : NULL
Version : ALL RW-HPS Version
VersionGame : 1.14

**Comment by deng-rui** [comment]
MD5

**Comment by driver1748** [comment]
MD5不可逆
虽然我不太懂，但是我的建议是类似mindustry服务端，直接采用原生加载，等到有更高效率的解决方案之前先凑合着用

**Comment by deng-rui** [comment]
> MD5不可逆
> 虽然我不太懂，但是我的建议是类似mindustry服务端，直接采用原生加载，等到有更高效率的解决方案之前先凑合着用

不是这样的哦

**Comment by deng-rui** [comment]
> > MD5不可逆
> > 虽然我不太懂，但是我的建议是类似mindustry服务端，直接采用原生加载，等到有更高效率的解决方案之前先凑合着用
> 
> 不是这样的哦

Luke采用的是MD5做校验码 服务器只给客户端发校验码以及Mod名字 客户端只是做校验

**Comment by deng-rui** [comment]
> > > MD5不可逆
> > > 虽然我不太懂，但是我的建议是类似mindustry服务端，直接采用原生加载，等到有更高效率的解决方案之前先凑合着用
> > 
> > 
> > 不是这样的哦
> 
> Luke采用的是MD5做校验码 服务器只给客户端发校验码以及Mod名字 客户端只是做校验

而且这个服务端没有模拟层 加载Mod也无法模拟玩家的移动 只能原封转发 所以直接计算校验MD5我想是最方便的

**Comment by driver1748** [comment]
好吧

**Comment by deng-rui** [comment]
已有暂替方案

**Comment by deng-rui** [comment]
请参见分支

**Comment by deng-rui** [comment]
主分支已完成
