### ISSUE TITLE
开始游戏后如果有同步会游戏速度加快的情况

### ISSUE THREAD

**Issue by npldys** [RW-HPS/RW-HPS#352]

**Comment by deng-rui** [comment]
？

**Comment by npldys** [comment]
无论在以前的1.14还是现在都有这个情况，在开始游戏后，如果出现同步游戏的情况可以会使得游戏的速率非常块，例如原来造一个建筑需要10秒，现在只需5秒，是游戏整体的倍速加快。
![Screenshot_20221229_100648](https://user-images.githubusercontent.com/118544146/209894568-690c0067-a65e-4add-8c4d-2fdf620b6e63.jpg)

**Comment by npldys** [comment]
Uploading Screenrecording_20221229_094656.mp4…

**Comment by deng-rui** [comment]
解决方案：
考虑后续采用游戏默认
100/6的 Tick
满足 60 Fps
