### ISSUE TITLE
用户手册的疏漏以及开服时遇到的一些问题

### ISSUE THREAD

**Issue by QVQSmile** [RW-HPS/RW-HPS#357]
用户手册中的开服教程，直接打开里面，讲了遇到第一个错误的应对方法，可是发行版中找不到data文件。
手册提供的版本链接404notfound。
data文件在运行server-all后会自动创建，但是还是遇到了相同的问题（第一个）。
仔细观察代码，显示下载一个压缩包，但是下载不下来，于是我找到了data文件中的该压缩包，无法解压，通过链接下载压缩包，显示没有此文件。

萌新小白，若有疑问或不足欢迎指出！

**Comment by deng-rui** [comment]
这块啊, 确实是维护者的锅

Ling当时写的时候还在进行 版本跨越, 没有统一制定版本号规范(实际上没有遵守)
然后我更新的时候就...(

目前不需要看第一个问题, 因为 `RW-HPS` 自动下载 ASS/RES 文件来配置

**Comment by deng-rui** [comment]
docs.rwhps.net
