### ISSUE TITLE
玩家重连会导致其他玩家全部断开连接

### ISSUE THREAD

**Issue by npldys** [RW-HPS/RW-HPS#365]
在房间人数比较多的情况下（比如超过10人）
如果有人断开连接并重连，会导致其他玩家全部断开连接。
![Screenshot_20230120_203801](https://user-images.githubusercontent.com/118544146/213841977-54f53bac-3b2c-4997-9ed5-96aaf64019cb.jpg)

玩家断开后如果重连，此时有几率会重连成功，可能此时人少会同步成功，但又会出现游戏速度变快的情况。
我出现这个现象的环境：房间人数达到22人，地图是自定义地图也是22人的。

另外我拿以前的1.14也试了下，只有开局同步导致游戏加速的情况，玩家断开重连不会导致其他玩家断开。

**Comment by deng-rui** [comment]
FIX

游戏速度恢复
