### ISSUE TITLE
same rwmod same server   smartphone can join PC HOST ， PC can't join phone

### ISSUE THREAD

**Issue by oceans-penguin** [RW-HPS/RW-HPS#372]
- Device: [e.g. huawei nova7 pro]
 - OS: [e.g. harmony]
 - Game Version [e.g. 1.15]
 - Server Version [e.g.1.1.0]

**Additional context**
![image](https://user-images.githubusercontent.com/81892455/214362926-0a415b67-5350-44bb-ab01-d41a955317b6.png)

![image](https://user-images.githubusercontent.com/81892455/214362693-d670f6fb-e8c3-4881-b892-1d6fefde7ab5.png)

**Comment by deng-rui** [comment]
很奇怪的Bug, 这个问题我也不清楚

**Comment by deng-rui** [comment]
Solutions
