### ISSUE TITLE
类房间服务器支持玩家使用自定义地图

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#373]
玩家可以在开发者开的服务器内，直接可以切换自己设备内的自定义地图文件，来进行游戏，而不是单纯服务器内内置的地图选择（参考RCN房间选择自定义地图）

**Comment by deng-rui** [comment]
很难, 服务器正常情况拿不到地图

**Comment by deng-rui** [comment]
除非使用 RELAY 否则 SERVER 协议不可能实现本功能, 如果协议支持, 问题会重新开始
