### ISSUE TITLE
[插件] mirai机器人多服务器互联

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#374]
可以分为主服务器和副服务器
## 主服务器：
主要登录QQ机器人，并且提供和其他副服务器通信服务，比如websocket，主要用于和群聊通信
#### 命令
并且主服务器可以执行某些命令，比如群主/管理员可以在机器人那里执行**高级权限命令**
例如：群聊内直接发送命令修改命令的文字

**群聊内只能管理员发送的比如：**
- 强制结束对局
- 强制开始游戏
- 强制在游戏中踢出某个人
- 强制返回房间（进行游戏中时，直接返回房间，重新开始游戏）
- 强制切换地图
- 强制把玩家切换队伍
- 强制修改/清空/加满玩家经济
- 强制清空某个玩家全部/某个单位
- 生成特定数量单位（位置坐标）
- ban某玩家
- ban某玩家ip
- kick某玩家
- kick某玩家ip
- 黑名单某玩家
- 黑名单某玩家ip

**群聊内玩家可发送的比如：**
- > 在线玩家包括：
> > - 返回游戏内在线玩家数量
> > - 以及全部玩家的：
> > > 名称
> > > 队伍信息
> > > 玩家几号位置
> > > 颜色
> > > ~~是否囤蛋~~
- > 游戏对局信息包括：
> > 对局时间
> > 对局人数
> > 对局状态
> > 对局地图
> > 对局开始/结束时间
> > 对局模式
> > 对局单位总数量等
## 副服务器：
可以和主服务器通信，列如副服务器对局失败与成功消息直接和主服务器告知，然后由主服务器来通过mirai往对应群聊（可自定义）内发送消息
### 消息内容可包括
- [x] 统计今日对局次数
- [x] 总场数
- [ ] 今日游戏时间
- [x] 当前对局总游戏时间
- [x] 游戏人数
- [x] 玩家名称
- [x] 玩家游戏时间
- [x] 玩家ip
- [x] 玩家归属地
- [ ] 玩家是否在黑名单
- [ ] 玩家总游戏时长
- [ ] 玩家是否有违规行为
- [x] 玩家胜利方与失败方
- [ ] 玩家击败单位数量（最高和最低）
- [x] 玩家名称是否违规
- [ ] ~~玩家手机号（线下真实他去！）~~
- [ ] 玩家本局游戏共造多少单位、队伍直观图（我记得1.15游戏内置了对局完成后可供参考的线形图，可以考虑获取下来，然后直接转发群聊）
- [x] 玩家对局地图（开始前与结束后两种地图）
- [x] 本局游戏录像（好像已经有了）

**Comment by deng-rui** [comment]
你来写

**Comment by Mitpoppy** [comment]
> 你来写

嘤嘤嘤，我相信你可以写的🌚

**Comment by 493505110** [comment]
> 然后由主服务器来通过go-cqhttp往对应群聊（可自定义）内发送消息
标题是`mirai`内容是`go-cqhttp`？

**Comment by Mitpoppy** [comment]
> > 然后由主服务器来通过go-cqhttp往对应群聊（可自定义）内发送消息  
> 
> 标题是`mirai`内容是`go-cqhttp`？

用go-cqhttp用多了打错了🌚

**Comment by deng-rui** [comment]
UPDATE

**Comment by deng-rui** [comment]
#254

**Comment by deng-rui** [comment]
PLAN-1

**Comment by deng-rui** [comment]
插件都可以调用, 不需要服务器去主动支持
