### ISSUE TITLE
WEB网页端一端多服管理

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#376]
~~**理想化的两种方式**~~
# 1. 主控多服（推荐）
顾名思义就是一个服务器开启WEB控制端（主控端），就是开启网页的那个服务器
然后另外其他服务器为联通端
## 理想实现原理
**主控**
负责开启网页端服务，并且开放联通其他服务器接口（建议是开放api接口，这样的话可以让别的云服务器上的服务器也可以对接WEB控制端，不然如果只是ws通信内网的服务端的话，无法照顾到其他云服务器的，~~（相信大家应该有好几个云服务器吧）~~）
**联通端**
负责与主控服务器通信，主控服务器上面的WEB网页后台可以直接控制联通的服务器上面的操作（也包括主控端服务器上面的操作），比如：开关服务器 运行命令 文件管理 MOD管理（好像重复了） 更改端口 编辑文件等功能
# 2. 独立单控多服
独立开发一个程序，这个程序可以开启WEB网页控制端，而全部服务器直接与这个程序进行通信
# 好处
如果我是想一个WEB网页端就能控制全部服务器的话，我就不再是需要每个服务器都开WEB网页端了，如果按现在的限制那如果都开就是要开4个WEB端，管理起来反而麻烦
## PS
我不太推荐第二种方法，当然如果有更好的解决方法，何乐而不为。不推荐的原因就是如果是面板服无法另开一个端口，再者就是nat vps服务器限制端口数量，如果另开端口作为WEB服务器，比较浪费可用端口数量（一般都是增加可用端口数量要花钱，~~比如鸽子 咕咕咕~~）

**Comment by deng-rui** [comment]
你来写前端

**Comment by Mitpoppy** [comment]
> 你来写前端

好家伙回复这么快🌚

**Comment by deng-rui** [comment]
目前采用 1 方案

前端由 @FiresonZ 来
后端喜闻乐见了

通讯协议走 WSS/WS, 用户数据交互由 POST 完成
默认保留控制台的50条消息

**Comment by Mitpoppy** [comment]
> 目前采用 1 方案
> 
> 前端由 @FiresonZ 来
> 后端喜闻乐见了
> 
> 通讯协议走 WSS/WS, 用户数据交互由 POST 完成
> 默认保留控制台的50条消息

我建议保留控制台多少条消息可以自定义
