### ISSUE TITLE
支持使用JS编写插件

### ISSUE THREAD

**Issue by zerodegress** [RW-HPS/RW-HPS#380]
# 缘由
用Kotlin和Java编写插件感觉有点浪费，而且事实上有时候插件实现的功能非常简单。
# 运行时选择
1.使用[Rhino](https://github.com/mozilla/rhino)，比较传统的JVM下的JS运行时，体积很小，只有1M多。
2.使用[GraalVM](https://www.graalvm.org/)，比较新的JVM下JS运行时，比较臃肿，只包含js的部分也有20M多（但是也许还可以支持其他语言，包括JVM语言和其他GraalVM支持的脚本语言）。
3.使用Nashorn，JDK自带，但是Java11开始已经不建议用了。
# 方案A
直接嵌入HPS（推荐）
## 插件形式
包含若干脚本文件，清单文件，配置文件，使用到的资源文件的压缩包，暂且称为**插件包**。
清单文件指示了插件的版本，主脚本和一些基本信息。
插件中与宿主HPS互动使用**钩子函数**，可以是事件处理器或者其他需要与HPS互动的函数。
插件应该被限制与HPS宿主的互动，只能访问指定的类型、接口等。
以上JS运行时均支持Promise，可以执行异步操作。
## 模块化
同一个插件包中js代码需要互调用。
由于之前提到的运行时都不支持esm，所以可以采用common js模块化（之前提到的JS运行时都自带common js模块加载器）。
## 对接
大体上可以跟原来Kotlin和Java编写插件的模式一样，并将钩子函数在插件的主脚本中通过module.exports暴露出来供HPS调用。
# 方案B
作为HPS事件处理服务器独立运行，HPS本身是事件处理的反向代理服务器。
~~抛开事实不谈，理论上可行~~
# 额外
也许可以考虑实时编译执行Typescript代码？不过感觉这样编写插件门槛又上来了。

**Comment by deng-rui** [comment]
我也有个想法，用Java自带的热编译来动态加载.java文件

**Comment by deng-rui** [comment]
> 
> 
> 
> 
> > 我也有个想法，用Java自带的热编译来动态加载.java文件
> 
> 这个可以用标准库里面的JavaCompiler搞吧，我这有个网上找到的例子：
> ```java
>     public Class<?> generate(String classFullName, String code, String jarFile) throws MalformedURLException, ClassNotFoundException {
>         JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
>         JavaFileObject fileObject = new JavaSourceFromString(classFullName, code);
>  
>         File root = new File(classRootDir);
>         if (!root.exists()) {
>             root.mkdirs();
>         }
>  
>         String jars = getJars(jarFile);
>         Iterable<String> options = Arrays.asList("-d", classRootDir, "-cp", jars + File.pathSeparator + classRootDir);
>         Iterable<? extends JavaFileObject> compilationUnits = Arrays.asList(fileObject);
>         JavaCompiler.CompilationTask task = compiler.getTask(null, null, null, options, null, compilationUnits);
>  
>         // 动态编译
>         boolean success = task.call();
>         if (!success) {
>             return null;
>         }
>         SLogger.info("compile success root path = " + root.getPath());
>         URL[] urls = new URL[]{root.toURI().toURL()};
>         // 设置父类加载器
>         URLClassLoader classLoader = new URLClassLoader(urls, ClassGenerator.class.getClassLoader());
>         return Class.forName(classFullName, true, classLoader);
>     }
> 
> ```

是的， 目前 RCN 热更新就是靠的这个 （）

**Comment by deng-rui** [comment]
使用 Nashorn
