### ISSUE TITLE
房间没有空位的安全问题

### ISSUE THREAD

**Issue by n9tank** [RW-HPS/RW-HPS#385]
在v2.0.0Dev31版本中出现。（别人的服务器)
1.房间没有空位，导致玩家无法加入。
通过 move 移除玩家，填充所有空位为ai，并退出服务器。
次要的:
2.无法踢出ai，只能通过move移除。

**Comment by deng-rui** [comment]
啊 有时间我看看

**Comment by deng-rui** [comment]
Fix Kick AI Error
