### ISSUE TITLE
关于玩家投降后服务器不会自动重新启动房间

### ISSUE THREAD

**Issue by DaiyunYang** [RW-HPS/RW-HPS#394]
**Describe the bug**

玩家投降后服务器不会自动重新启动房间

**To Reproduce**

1. 房间内存在至少两个不同队伍的玩家
2. 开始游戏后一方投降
3. 双方退出后等待几分钟再进入服务器,服务器仍停留在上次退出时的状态

**Expected behavior**

投降后xx秒服务器自动重新启动

**Pplease complete the following information:**

 - OS: windows10
 - Game Version 1.15
 - Server Version 2.0.0-M3

**Comment by DaiyunYang** [comment]
(或者添加一个手动结束游戏的指令?)

**Comment by DaiyunYang** [comment]
qwq本来想自己看看能不能找到bug在哪里然后pr骗点贡献然后看不懂架构于是乖乖提了issue（

**Comment by deng-rui** [comment]
FIX
