### ISSUE TITLE
RCN 服务器增加回到上一个房间命令

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#404]
如果我在一个房间中途或者刚进入时闪退
我可以通过 RCN 服务器输入命令回到上一个我加入的房间
或者输入命令后显示最近加入的房间的房间号（按顺序排列）

**Comment by deng-rui** [comment]
实现
新命令
old
与 new 等命令同地方输入
效果是返回最后一次加入的房间，如果房间关闭，那么用上次的配置创建一个房间

**Comment by Mitpoppy** [comment]
> 实现
> 新命令
> old
> 与 new 等命令同地方输入
> 效果是返回最后一次加入的房间，如果房间关闭，那么用上次的配置创建一个房间

你怕是吃了金坷垃了吧，这么快😨
