### ISSUE TITLE
old命令无效

### ISSUE THREAD

**Issue by Mitpoppy** [RW-HPS/RW-HPS#405]
`实现
新命令
old
与 new 等命令同地方输入
效果是返回最后一次加入的房间，如果房间关闭，那么用上次的配置创建一个房间
最初由 deng-rui 在 https://github.com/RW-HPS/RW-HPS/issues/404#issuecomment-1545919142 发布_`

该命令使用后没有效果

**Comment by deng-rui** [comment]
还没更新
