### ISSUE TITLE
真实玩家全部断开连接，房间只剩下ai时，是否考虑服务器重启机制？

### ISSUE THREAD

**Issue by x-xiao98** [RW-HPS/RW-HPS#408]
经常遇到有人进了服务器，加了几个ai开始游戏没多久就退出了。这种情况下，ai们会互相打一直到游戏最大时间。这段时间别人也都使用不了服务器，非常浪费资源。

能否增加该机制，当房间只剩下ai时，服务器超过一段时间自动重启？（这项功能本身也可以做成一项配置）

**Comment by deng-rui** [comment]
这是个设计失误

**Comment by deng-rui** [comment]
Add Config
[MaxOnlyAIGameIngTime : 7200]
