### ISSUE TITLE
增加服务器定时数据同步机制

### ISSUE THREAD

**Issue by x-xiao98** [RW-HPS/RW-HPS#423]
由于一些原因(客户端修改本地数据，或是其他原因)会导致客户端的数据和服务端不一样，比如金钱，单位等。导致玩家数据不一致造成十分不好的游戏体验，常常一局游戏打下来，每个人看到的结局是不一样的。能否增加定时任务，每隔一段时间服务端向所有客户端同步一次数据，或者是增加命令手动触发？

**Comment by deng-rui** [comment]
这玩意怎么写, 没什么用啊
默认同步多次失败就摆烂了

**Comment by deng-rui** [comment]
有的客户端自己瞎jb改, 然后不理服务器的同步包, 你就算发了也没意义
就向给聋子说话一样

**Comment by deng-rui** [comment]
讨论出 有更好方案(结果)后重启
