### ISSUE TITLE
new command: nuke

### ISSUE THREAD

**Issue by StefanoB2018** [RW-HPS/RW-HPS#449]
nuke at point (ServerCommands.kt)
short implementation of .summon nuke

nuke < PositionX> < PositionY>

![Screenshot_2023-07-08-15-56-01-564-edit_com.corrodinggames.rts.jpg](https://github.com/RW-HPS/RW-HPS/assets/81710193/dc689086-869d-4132-8b6f-2db9308e3856)

ex:
input: .nuke 200 100
output:  spawned nuke at x:200 y:100

**Comment by deng-rui** [comment]
nuke好像是个抛物体，我也不知道怎么搞

**Comment by StefanoB2018** [comment]
> nuke好像是个抛物体，我也不知道怎么搞

那summon nuke 是怎么实现的？（点地图那个）

**Comment by deng-rui** [comment]
> > nuke好像是个抛物体，我也不知道怎么搞
> 
> 那summon nuke 是怎么实现的？（点地图那个）

没这个啊

**Comment by StefanoB2018** [comment]
> > > nuke好像是个抛物体，我也不知道怎么搞
> > 
> > 那summon nuke 是怎么实现的？（点地图那个）
> 
> 没这个啊

诶，真的没。
