### ISSUE TITLE
text decoration

### ISSUE THREAD

**Issue by StefanoB2018** [RW-HPS/RW-HPS#452]
eg. 
**Hello world**
_Hello world_
+colors
![Screenshot_2023-07-09-04-39-02-191-edit_com.corrodinggames.rts.jpg](https://github.com/RW-HPS/RW-HPS/assets/81710193/13856dab-7988-44bd-a8cf-b75da45bf396)

**Comment by deng-rui** [comment]
不支持字体格式更改， 这部分取决于官方字体限制

颜色不建议更改，因为可以靠颜色区分玩家
