### ISSUE TITLE
玩家发送GAMECOMMAND_RECEIVE包时的业务处理方法

### ISSUE THREAD

**Issue by x-xiao98** [RW-HPS/RW-HPS#453]
我在代码中只发现了GameVersionServer.receiveCommand方法可用来处理玩家相关游戏操作。但发现个问题，假如一共10个玩家，当某个玩家发送GAMECOMMAND_RECEIVE包时，GameVersionServer.receiveCommand方法会被调用十次(迭代了所有玩家)，并且在GameVersionServer.receiveCommand中无法区分是谁发送的包，考虑receiveCommand方法增加发送者的参数。用来做业务时，可正确区分操作者。或者增加像GameVersionServer.receiveChat一样的方法也可以，只有操作者才会调用，而不是全部玩家遍历调用

**Comment by deng-rui** [comment]
1. 不会迭代，每个玩家依靠 GameServer实例区分，且方法非静态
2. 不需要增加，理由如上
