### ISSUE TITLE
在服务器内有玩家时,HttpApi无法获取游戏信息

### ISSUE THREAD

**Issue by 493505110** [RW-HPS/RW-HPS#471]
路径: `/HttpApi/api/get/info/GameInfo`

![image](https://github.com/RW-HPS/RW-HPS/assets/29498336/0347704f-d2a6-4d24-8751-b38a5d412430)
服务器内无玩家时
![Screenshot_2023-07-30-21-46-33-773_com corrodinggames rts](https://github.com/RW-HPS/RW-HPS/assets/29498336/5f6d7758-f6cf-48ae-80e0-4b1013578836)
![image](https://github.com/RW-HPS/RW-HPS/assets/29498336/26951653-52b9-45b6-b82c-f2f2014af223)
玩家加入服务器后

界面一直在加载,似乎有什么东西死循环了
但是我通过断点找不到~~也有可能是我技术问题~~

**Comment by deng-rui** [comment]
可能是序列化炸了
