### ISSUE TITLE
RW-HPS的源代码warnings过多

### ISSUE THREAD

**Issue by 493505110** [RW-HPS/RW-HPS#472]
![image](https://github.com/RW-HPS/RW-HPS/assets/29498336/9e17b8e0-bc74-42b4-9472-e770dd38ada9)
![image](https://github.com/RW-HPS/RW-HPS/assets/29498336/86cb7eb9-8c39-4fa0-9fb1-839077015f4d)
虽然不影响编译，但是看着这些warnings挺烦人的

**Comment by 493505110** [comment]
并且存在一些未使用变量,不知道是之前使用现在不使用的还是别的什么原因？

**Comment by deng-rui** [comment]
有一部分是RCN用的
