### ISSUE TITLE
移动指令响应迟钝

### ISSUE THREAD

**Issue by ssw324** [RW-HPS/RW-HPS#487]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

服务端有时会出现延迟很低，移动指令却响应迟钝的问题，一般以某一整个hps-server为单位出现，而不是以某一场战斗，因为使用gameover指令强制重启房间后问题依旧存在，只有在ctrl+c重开hps后问题有概率改善。服务器是Ubuntu系统，有2个vcpu和2G内存，cpu内存占用都不超过10%，无swap分区。
我想这不正常，因为我并没有开四个hps，也没有把四个hps都压缩在swap虚拟内存上。据尝试，3.0M4和2.0.0都有概率出现该问题

### 日志文件

无时间点，如果不关闭再重启就会一直这样

**Comment by deng-rui** [comment]
解决问题
