### ISSUE TITLE
still waiting on一个不存在的人

### ISSUE THREAD

**Issue by ssw324** [RW-HPS/RW-HPS#488]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

still waiting on一个不存在的人，一般发生在3.0M4版本，该人掉线N/A后再被踢出房间时发生

### 日志文件

无

### 截图

![Uploading Screenshot 2023-12-13 155642.png…]()

**Comment by ssw324** [comment]
![Uploading Screenshot 2023-12-13 155642.png…]()

**Comment by deng-rui** [comment]
需要更多信息, 图片未上传

**Comment by ssw324** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RW-HPS/RW-HPS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月13日(星期三) 晚上11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RW-HPS/RW-HPS] still waiting (Issue #488)





 
需要更多信息, 图片未上传

**Comment by ssw324** [comment]
不是发错了，刚刚发成另一个bug




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RW-HPS/RW-HPS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月13日(星期三) 晚上11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RW-HPS/RW-HPS] still waiting (Issue #488)





 
需要更多信息, 图片未上传

**Comment by deng-rui** [comment]
![Uploading cf759240e69c52d9a7ecf26942d21d24.png…]()

**Comment by deng-rui** [comment]
![cf759240e69c52d9a7ecf26942d21d24](https://github.com/RW-HPS/RW-HPS/assets/39623218/3a043d7b-9c2d-4998-9cff-ebd1aae2335d)
