### ISSUE TITLE
无限核弹

### ISSUE THREAD

**Issue by ssw324** [RW-HPS/RW-HPS#489]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

加入核弹指令后，房间里任何一位玩家都可以无限放核弹，这会破坏游戏公平性，以及导致服务器崩溃。

### 日志文件

无

**Comment by deng-rui** [comment]
脱了很长时间，才想起来回issue，抱歉

我没记错的话，3.0.0-m不是写了吗，为什么还会有，这不应该，需要复现
