### ISSUE TITLE
需要一键混战

### ISSUE THREAD

**Issue by ssw324** [RW-HPS/RW-HPS#490]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

**Comment by deng-rui** [comment]
FFA是游戏模式, 目前暂时无此模式计划

**Comment by ssw324** [comment]
我只想输入.ffa以后所有玩家按顺序把队伍排列好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月13日(周三) 晚上11:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RW-HPS/RW-HPS] 需要ffa指令 (Issue #490)




 
FFA是游戏模式, 目前暂时无此模式计划
