### ISSUE TITLE
HttpApi需要支持地图切换

### ISSUE THREAD

**Issue by 1091062720** [RW-HPS/RW-HPS#497]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

希望可以用HttpApi切换地图， 现在可以查看地图，执行切换地图命令没效果，但是在游戏客户端内可以正常切换。

**Comment by deng-rui** [comment]
需要HTTPAPI支持传入url, 来自动下载地图并加载
需要HTTPAPI支持通过客户端命令修改地图

**Comment by deng-rui** [comment]
已支持，需要通过api中的客户端命令完成
