### ISSUE TITLE
增加JS插件鲁棒性

### ISSUE THREAD

**Issue by zerodegress** [RW-HPS/RW-HPS#504]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

目前JS插件如果加载部分插件失败会导致所有插件挂掉，如果做一些额外的异常检查可以避免这种情况。

WASM特性对于JS插件不是必须的，所以有时候如果wasm加载失败了应该可以忽略掉。

并且注意到，在GraalVM JDK（测试时使用GraalVM JDK17）下需要自行安装graaljs和wasm（Graal官方未提供wasm预编译包，所以安装WASM更加困难），这种情况下特别容易因为WASM特性缺失而无法加载。（也许需要对使用GraalVM运行RW-HPS的用户进行提示）

**Comment by deng-rui** [comment]
那 怎么办呢
我也不知道怎么写
