### ISSUE TITLE
120fps.jar版本开久了仍然出现cpu占用99.9%的情况

### ISSUE THREAD

**Issue by ssw324** [RW-HPS/RW-HPS#508]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

刚安装的一段时候还好，房间还是战斗都cpu很低。然而强行关闭再开启几次服务器，或者是gameover指令卡住以后强行重启服务器，之后就出现服务器0人空载时占用99%。战斗中cpu占用还是很正常，也很低，然而一返回房间就会99%cpu占用。至少在2个服务器上出现这样的情况，目前解决方法只能重装服务器系统并重新下载java

### 日志文件

无

**Comment by deng-rui** [comment]
#503
