### ISSUE TITLE
Server房间内uplist请求

### ISSUE THREAD

**Issue by Maple212** [RW-HPS/RW-HPS#554]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

server房间内不能直接在对话框输入某代码来上列表

### 有什么好的想法？

有些人开服务器希望给自己认识的人玩，但是由于自己不能长时间在线管理服务器导致服务器要么不在列表或者一直在列表，这样可能会导致人数不够或者有不怀好意的人进房间瞎搞，所以为了群友能有一个良好的体验，希望作者组能出一个server房间内uplist功能，真的很需要，如果能出真的很感谢！

**Comment by deng-rui** [comment]
.toup
.tonp
