### ISSUE TITLE
游戏中有人中途退出无法踢掉

### ISSUE THREAD

**Issue by Maple212** [RW-HPS/RW-HPS#565]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

游戏中途玩家断连后无法踢出房间，房间内指令无法使用，后台指令无法使用，后台无报错，gameover仍旧生效，程序不关闭的情况下断连玩家会一直在房间内，无法清除

### 日志文件

无报错，日志文件无反应

**Comment by Mitpoppy** [comment]
补充

Uploading QQ视频_09638d4fc812207af726aff350b6879e.mp4…

**Comment by deng-rui** [comment]
可能是玩家退出后con变量null导致后续暴毙

**Comment by deng-rui** [comment]
修复
