### ISSUE TITLE
建议修改addmoney的实现方式

### ISSUE THREAD

**Issue by x-xiao98** [RW-HPS/RW-HPS#601]
### 说说你遇到的问题？

目前addmoney实现方式具有延迟性(主要是服务器sync的间隔比较长)，是否可以换成即时的？(参考超级建造者的增加资金功能)

**Comment by deng-rui** [comment]
很难, 本地修改/云端修改截然不同, 本地沙盒修改并不会有同步吗但是云端有, 这个无解

**Comment by x-xiao98** [comment]
DR你好。在rwhps中，使用summon命令可以生成超级建造者。超级建造者有一项增加资金的命令，当点击以后，会给服务器发生指令通知云端给玩家增加资金。这个资金是即时的，并且对于其他玩家来说也是即时可见的。本恩人能力有限，无法破译数据包的内容。这个应该理论上也是可以的，毕竟当我执行任意命令后之后(例如修建建筑、升级、爆兵、移动等)，其他玩家也是即时可见的，也不需要服务器延时的sync

**Comment by deng-rui** [comment]
？ 我不是记得HPS生成超级建造者会闪退吗

**Comment by deng-rui** [comment]
来个视频我看看

**Comment by Minxyzgo** [comment]
> ？ 我不是记得HPS生成超级建造者会闪退吗

可以的，之前看到有人调出来过，甚至还能随意修改队伍

**Comment by Mitpoppy** [comment]
> ？ 我不是记得HPS生成超级建造者会闪退吗

你记性不好，可以用的🙃

**Comment by deng-rui** [comment]
> > ？ 我不是记得HPS生成超级建造者会闪退吗
> 
> 可以的，之前看到有人调出来过，甚至还能随意修改队伍

那不是卡沙盒卡的吗，当时我写summon的时候测过沙盒建造，一点就崩，所以我才强行调用沙盒建造者的action走同步

**Comment by deng-rui** [comment]
> > ？ 我不是记得HPS生成超级建造者会闪退吗
> 
> 你记性不好，可以用的🙃

来个视频我看看

**Comment by Mitpoppy** [comment]
> > > ？ 我不是记得HPS生成超级建造者会闪退吗
> > 
> > 你记性不好，可以用的🙃
> 
> 来个视频我看看

我没有，我记得之前群里看见过有人用了🙃

**Comment by deng-rui** [comment]
我草? 能用?

**Comment by deng-rui** [comment]
建议使用
.summon editorOrBuilder

目前`RW-HPS` 使用的就是沙盒方案, 但是我懒得研究了
