### ISSUE TITLE
命令STOP无效

### ISSUE THREAD

**Issue by deng-rui** [RW-HPS/RW-HPS#84]

**Comment by MZZZ-T** [comment]
请使用exit命令来关闭服务器

**Comment by deng-rui** [comment]
> 请使用exit命令来关闭服务器

¿

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/161384951-ff15d70f-3df7-4c0b-9e38-22e122bf8156.png)
(不知道为什么，有点想笑)

**Comment by MZZZ-T** [comment]
> ![image](https://user-images.githubusercontent.com/29498336/161384951-ff15d70f-3df7-4c0b-9e38-22e122bf8156.png) (不知道为什么，有点想笑)

事实上我是一个新手，我只是看到help列表里面有说exit是退出服务器的指令（所以stop是拿来干嘛的？

**Comment by deng-rui** [comment]
放弃
用途不大
