### ISSUE TITLE
The app cannot be found after the server loads the map

### ISSUE THREAD

**Issue by rgzn-aiyun** [RW-HPS/RW-HPS#97]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

*Pplease complete the following information:**
 - Game Version [e.g. 1.14]
 - Server Version [e.g.1.4.0.6]

**Additional context**

**Comment by rgzn-aiyun** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> _Pplease complete the following information:_*
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Game Version [e.g. 1.14]
> * Server Version [e.g.1.4.0.6]
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by deng-rui** [comment]
.maps and .map number
You can enter. Help in the game

**Comment by rgzn-aiyun** [comment]
Server can be displayed.

**Comment by deng-rui** [comment]
> Server can be displayed.

I don't think I understand

**Comment by rgzn-aiyun** [comment]
App could not find the loaded map

**Comment by deng-rui** [comment]
Put the map under data/maps
Then set readmap to true in config.json

**Comment by rgzn-aiyun** [comment]
Yeah, it's so amazing. App can't find it.

**Comment by deng-rui** [comment]
我想你可以使用中文
I think you can use Chinese

**Comment by deng-rui** [comment]
如果您是启动了服务器然后放的地图 你需要在服务器的控制台使用reloadmaps(不是在客户端)来重新加载一下地图 或者用ctrl+c来重新启动一下服务器 然后就可以使用.maps查看

If you start the server and put the map, you need to use reloadmaps (not on the client) on the server console to reload the map, or use Ctrl + C to restart the server, and then you can use .maps to view the map

**Comment by rgzn-aiyun** [comment]
Maps show the map correctly, but the app doesn't work?

**Comment by deng-rui** [comment]
> Maps show the map correctly, but the app doesn't work?

What doesn't work

**Comment by deng-rui** [comment]
> Maps show the map correctly, but the app doesn't work?

If you are a room administrator, there will be problems in the map display of your interface, but the server does load it

**Comment by rgzn-aiyun** [comment]
In the app, the map list does not have a map loaded by the server.

**Comment by deng-rui** [comment]
> In the app, the map list does not have a map loaded by the server.

Is it in the default map selection? The default map selection is no custom map

**Comment by deng-rui** [comment]
So you need to use. Maps to view the map, and use  
.Map+ space + map serial number to switch

**Comment by deng-rui** [comment]
The server judges the map based on the suffix. If your map does not end with. TMX, the server will consider it invalid

**Comment by rgzn-aiyun** [comment]
Unknown command. Check help

**Comment by rgzn-aiyun** [comment]
map 6?

**Comment by deng-rui** [comment]
.maps view map list
for example
I type. Maps to show it
地图序号: 0 地图名称: aaaa.tmx
地图序号: 1 地图名称: a.tmx
Then I want to change a.tmx
Enter .map 1

**Comment by deng-rui** [comment]
Maybe the translation I used translated the command into a word, causing the server not to recognize the command after you copied it  
:(

**Comment by deng-rui** [comment]
The server command does not need a decimal point, but the client command needs a decimal point

**Comment by rgzn-aiyun** [comment]
map 1
[] Unknown command. Check help

**Comment by deng-rui** [comment]
.map 1
!!!!!
There is a decimal point in front of it !!!

**Comment by rgzn-aiyun** [comment]
The app is okay, but the server does not have this command?

**Comment by rgzn-aiyun** [comment]
[] [test]: .map 20
[] [test]: -qc -start
[] Server Gameover completed
map 20
[] Unknown command. Check help

**Comment by deng-rui** [comment]
> The app is okay, but the server does not have this command?

Enter help in server control (no decimal point)
Client input .help (with decimal point)

**Comment by deng-rui** [comment]
> [] [test]: .map 20
> [] [test]: -qc -start
> [] Server Gameover completed
> map 20
> [] Unknown command. Check help

Didn't you find the map? Cause the game to crash

**Comment by rgzn-aiyun** [comment]
The server only has maps command.

**Comment by rgzn-aiyun** [comment]
> > [] [test]: .map 20
> > [] [test]: -qc -start
> > [] Server Gameover completed
> > map 20
> > [] Unknown command. Check help
> 
> Didn't you find the map? Cause the game to crash

There is only one person, leading to an early end of the game

**Comment by deng-rui** [comment]
> > > [] [test]: .map 20
> > > [] [test]: -qc -start
> > > [] Server Gameover completed
> > > map 20
> > > [] Unknown command. Check help
> > 
> > 
> > Didn't you find the map? Cause the game to crash
> 
> There is only one person, leading to an early end of the game

The server has a countdown

**Comment by deng-rui** [comment]
> > > [] [test]: .map 20
> > > [] [test]: -qc -start
> > > [] Server Gameover completed
> > > map 20
> > > [] Unknown command. Check help
> > 
> > 
> > Didn't you find the map? Cause the game to crash
> 
> There is only one person, leading to an early end of the game

If only one person resets the server in one minute, if all players quit, it will be reset directly

**Comment by rgzn-aiyun** [comment]
It's much more fun to add humans and machines.

**Comment by deng-rui** [comment]
> It's much more fun to add humans and machines.

yes
